### ISSUE TITLE
closeOnSelect=false does not work if onItemSelect triggers a $digest cycle

### ISSUE THREAD

**Issue by DavidCasillasRivero** [dotansimha/angularjs-dropdown-multiselect#101]
I have set `closeOnSelect` and `closeOnDeselect` to false. This was working Ok and the multi selector keeps opened as expected until I click on the drop down button or anywhere outside the selector. 

The problem comes when I set  callbacks for `onItemSelect` and `onItemDeselect`. The action implemented in this functions  triggers an angular `$diggest` cycle and this in turn forces the multi selector to close.

**Comment by pkempenaers** [comment]
duplicate #101
