### ISSUE TITLE
Array of string

### ISSUE THREAD

**Issue by kulwinder156** [dotansimha/angularjs-dropdown-multiselect#102]
We can't bind array of strings.

var arr = ['David','Jhon','Lisa'].

My webApi returns array of string for many methods.

Thanks,
Kulwinder

**Comment by toderini** [comment]
Agree with this. Sometimes we need to use simple string arrays.
Is there any way to do this with the current version of the project without any hack?

**Comment by alkeshattal** [comment]
Incase the options list is not fixed, but infact a REST resource,  we cannot change the producer to tailor the JSON in our required format. This I think needs to be taken up so as to handle simple list of array.

**Comment by mnewmedia** [comment]
💯

**Comment by pkempenaers** [comment]
Currently possible in 2.0.0-beta

**Comment by mnewmedia** [comment]
Thank you @pkempenaers 🎉 🍰 🎈
