### ISSUE TITLE
Dropdown doesn't close if you have two multiselect instance.

### ISSUE THREAD

**Issue by sanjaybhaskar** [dotansimha/angularjs-dropdown-multiselect#104]
The dropdown doesn't close if you click on the different instance of multiselect.

Lets assume that i have two Multiselect item in a page. Click on the first Multiselect item. It opens the dropdown and click on the second mutiselect item. The opened dropdown doesn't close. Now this will result in having two dropdown open.

Only way to close the dropdown is to click the multiselect button or click on the page outside scope of multiselect.

Could you please help me to perform this functionality.

**Comment by arsinawaz** [comment]
+1

**Comment by deifos** [comment]
I'm running two drop downs one depending on the selection of the other and don't have that issue, have you find a solution, can you share some code to see if I can help.
