### ISSUE TITLE
ordering in the dropdown doesn't seem to work

### ISSUE THREAD

**Issue by k-hu** [dotansimha/angularjs-dropdown-multiselect#109]
Hi there,

I have a list of items to show under the dropdown, grouped into 3 groups, however the ordering of those items, either globally or within the group doesn't seem to be in ascending or descending order. The original data source was ordered though. Providing orderBy in settings doesn't seem to help.

Thanks for your time.

**Comment by pkempenaers** [comment]
this should be working fine by now
