### ISSUE TITLE
drop-down button cant Closed when click on Chart

### ISSUE THREAD

**Issue by PoppyPham** [dotansimha/angularjs-dropdown-multiselect#117]
I used a D3 Chart below drop-down button.
When drop-down is opened, and over on chart region, then I clicked on chart region it can't closing in chrome and firefox. But on IE it work well.
I see this problems in console log debug.
"Uncaught TypeError: target.className.split is not a function"
and problems at this comand: _.contains(target.className.split(" ")
and I add new condittion, 
_.isString(target.1className) &&  _.contains(target.className.split(" ") it work well on

**Comment by nadouani** [comment]
+1

**Comment by jparmenter** [comment]
+1

**Comment by Delysid** [comment]
I have the same problem with highcharts

**Comment by pkempenaers** [comment]
Hi guys just for your information on my fork this is working as you can see in [my plunker](http://plnkr.co/edit/xWQCgwUMigHheKmo1UjG?p=preview)

You can find documentation for my fork [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/) and the repo [here](https://github.com/myforce/angularjs-dropdown-multiselect).
I'm also actively maintaining my fork so when you have any issues you may create them there.

**Comment by nadouani** [comment]
@pkempenaers sounds good to me. I'll use your fork

**Comment by ChandraKantPaliwal** [comment]
@pkempenaers sounds good to me. I'll also use your fork thanks :+1:
