### ISSUE TITLE
Preselection Issue. isChecked seems to fail

### ISSUE THREAD

**Issue by abimelex** [dotansimha/angularjs-dropdown-multiselect#12]
I wrote an app with several simple dropdown selections inside ng-repeat loop. The population of options works very well and the count of preselected items also. I use async request to achieve that. But the preselected Items are not marked as preselected. So I think it has something to do with the isChecked() function. Is that possible?

**Comment by kmukthi** [comment]
http://plnkr.co/edit/nIPGhEghkTff1iJZ0uRu?p=preview

**Comment by Bhavin305** [comment]
Please update isChecked function like this 

$scope.isChecked = function (id) {
                    if ($scope.singleSelection) {
                        if($scope.selectedModel === undefined)
                            {
                                $scope.selectedModel={};
                            }
                        return $scope.selectedModel !== null &&    angular.isDefined($scope.selectedModel[$scope.settings.idProp]) && $scope.selectedModel[$scope.settings.idProp] === getFindObj(id)[$scope.settings.idProp];
                    }
                    if($scope.selectedModel === undefined)
                    {
                        $scope.selectedModel=[];
                    }
                    return _.findIndex($scope.selectedModel, getFindObj(id)) !== -1;
                };

**Comment by pkempenaers** [comment]
I can change the selection from outside of the directive as you can see in [this plunker](http://plnkr.co/edit/y50EhdVoTeXA5UpdrnYm?p=preview).

I'm going to close this issue. If you have any other issues don't hesitate to comment and I'll see what I can do.
