### ISSUE TITLE
Can not load bootstrap glyphicons 

### ISSUE THREAD

**Issue by artgryn** [dotansimha/angularjs-dropdown-multiselect#127]
Directive works fine, but constantly getting two errors in a  console.
`GET http://localhost:8080/fonts/glyphicons-halflings-regular.woff`
`GET http://localhost:8080/fonts/glyphicons-halflings-regular.ttf`

**Comment by Darksoulsong** [comment]
I second that. Is there an option to customize the icons? What if I want to use font-awesome, for example?

**Comment by odedfos** [comment]
+1 for customizing this. I need font-awesome as well

**Comment by aszharite** [comment]
+1
