### ISSUE TITLE
$scope.selectedModel is undefined

### ISSUE THREAD

**Issue by Lasto13** [dotansimha/angularjs-dropdown-multiselect#128]
Hello, ... I get error in the tittle which is 
$scope.selectedModel is undefined, at 
angularjs-dropdown-multiselect.js:277:25
When I try to select/deselect one/all of the items repeated in dropdown. 
I wasnt abble to find solution of this anywhere. I included Lodash and also fixed error in GetButtonText function in .dir, as was solved in other issue at Git. 

Thx for any help

**Comment by GenisDiaz** [comment]
Hi @Lasto13 

You must initialize before object of selected-model.

**Comment by Lasto13** [comment]
its ok now, ... btw the best dropdown. I use it a lot
