### ISSUE TITLE
error "GetButtonText()" lexers Angularjs

### ISSUE THREAD

**Issue by ruben-dev** [dotansimha/angularjs-dropdown-multiselect#129]
Hi, I have a problem with your library, I changed the lexers in Angularjs and I have an error on this method "GetButtonText()"

there a way to fix it?

**Comment by preston** [comment]
I have the same issue. No clue what the issue is. :(

**Comment by ruben-dev** [comment]
Hi

I fixed , replacing :

// angularjs-dropdown-multiselect.js line 55

element.html(template);

to:

// angularjs-dropdown-multiselect.js line 55

return(template);

2015-08-06 19:32 GMT-05:00 Preston Lee <notifications@github.com>:
