### ISSUE TITLE
On deselcting element from drodown removing it from actual option array.

### ISSUE THREAD

**Issue by pankajparkar** [dotansimha/angularjs-dropdown-multiselect#136]
I tried to make a plunkr from the demo page. It doesn't looks working. On deselecting array it removes that array element from the actual array of controller scope variable.

[Plunkr Here](http://plnkr.co/edit/BVCg8ifCFCyiDenVBn2C?p=preview)

**Comment by pkempenaers** [comment]
In your plunker selected-model and options are the same array
