### ISSUE TITLE
Text of selected options

### ISSUE THREAD

**Issue by RafaMedina** [dotansimha/angularjs-dropdown-multiselect#138]
Hi,

is there a way to get the text of selected options?

Regards

**Comment by rajkumarpb** [comment]
With the below code you can get the select data JSON.

    // MultiSelect Drop down select - Event
    $scope.selecEvents = {
      onItemSelect: function(property) {
        console.log('select > ' +property);
      },

      onItemDeselect: function(property) {
        console.log('deselect : ' +property);
      }
    }

print the property and see the text which you need and use it!! Make sure you add these events while creating multi-select!

**Comment by RafaMedina** [comment]
Thank you @rajkumarpb
