### ISSUE TITLE
onBlur/onClose Event

### ISSUE THREAD

**Issue by bsssp** [dotansimha/angularjs-dropdown-multiselect#140]
can execute a event when the User leave the select element and it will be close, also a onBlur or onClose Event.
![onblur_1](https://cloud.githubusercontent.com/assets/13966807/9473670/5502975a-4b5c-11e5-9f4e-a89219d0f0ee.PNG)
![onblur_2](https://cloud.githubusercontent.com/assets/13966807/9473669/550128c0-4b5c-11e5-9046-f63392b828f6.PNG)

Many thanks

**Comment by resh2302** [comment]
@bsssp thanks for bringing this up, I was looking for an implementation as well. 

@dotansimha I have tried implementing the onClose event [here](https://github.com/resh2302/angularjs-dropdown-multiselect/commit/3e713309521002b7a9ed5acdfb469d952701ad66)
I had to do a little more than the code above. If you think it works well, please consider merging. 

Thanks.

**Comment by yogamaha** [comment]
Would be nice if this section is added in the documentation page of the library.

**Comment by collaborator99** [comment]
An onClose event would be very useful for our project. @dotansimha, do you have plans to do this?

**Comment by pkempenaers** [comment]
onClose has been implemented
