### ISSUE TITLE
Async data not loading

### ISSUE THREAD

**Issue by jasongooey** [dotansimha/angularjs-dropdown-multiselect#141]
I have a feeling that my issue is something minor that I am overlooking.  The dropdown will render but I have an empty list.  I know my collection is being populated because it works with a regular select dropdown.  The formatting got a bit messy here but I think it captures the bulk of my code.

Here is my **Jade:**

``` jade
.form-group.required
            label.required(for='platform') Platform
            select.form-control(ng-dropdown-multiselect='', ng-disabled='{{locked}}', selected-model='selectedC', options="c", extra-settings="multiSelectOptions")
```

I followed previous advice and initialized the selected-model scope variable to an empty array.  Here is the structure of my model:

``` javascript
 function System (id, name, value) {
   "use strict";
   this.id = id;
   this.name = name;
   this.value = value;
}
```

My multiSelectOptions parameter looks like this:

``` javascript
$scope.multiSelectOptions = {
        displayProp: 'name'
    };
```

Finally here is the code that I use to populate my collection.  I obfuscated it a bit but it should get the point across:

``` javascript
client.getReferenceData(function(result) {
        refdata = result;
        $scope.a= result[0];
        $scope.b = result[1];
        $scope.c = result[2];
        $scope.d = result[3];
        $scope.e = result[4];
        $scope.f = result[5];
        $scope.g  = result[6];

    });
```

Under hood I use restangular to get the data and then call the callback function.  

The result is an empty select box.

Again I think this is a case of my eyes deceiving me after looking at this for so long.

Any help would be greatly appreciated.

**Comment by pkempenaers** [comment]
options should be an array. in client.getReferenceData you set c to result[2] if that isn't an array you'll have no options
