### ISSUE TITLE
Multiple event handler hookups and error thrown if parent.className is not a string

### ISSUE THREAD

**Issue by patrix2001** [dotansimha/angularjs-dropdown-multiselect#143]
I've noticed that at line 150 it hooks up the document.click event every time that code is run, and it never de-registers the event. Therefore every time a page (with the multi-select control) is visited the code appends the handler to what’s already there. Causing the event handler to run N times.

At line 155 if target.className is not a string, it throws an exception saying "target.className.split" is not a function. I get this error when clicking on a SVG object.

I could provide a JS fiddle of the issue or I could fix it and submit a pull request, would you have a preference?

**Comment by pkempenaers** [comment]
the error is resolved, the other part is
#260
