### ISSUE TITLE
disabled options

### ISSUE THREAD

**Issue by caffeineaddiction** [dotansimha/angularjs-dropdown-multiselect#144]
I would like to be able to list options but not have them be select-able.

For example, if you had a list of paint ['red', 'green', 'blue'] and you wanted to show all 3 as options but at the moment you are all out of red but have some on back order ... it would be nice to show red as an option but disabled.

**Comment by caffeineaddiction** [comment]
I implemented this with the following code: http://codepad.org/ZCaRVLWQ

**Comment by Ashviniv** [comment]
@caffeineaddiction Here is the PR[#189](https://github.com/dotansimha/angularjs-dropdown-multiselect/pull/189) exists for the disable dropdown option.
