### ISSUE TITLE
feature request: keyboard support

### ISSUE THREAD

**Issue by kelkes** [dotansimha/angularjs-dropdown-multiselect#15]
Would be great to have keyboard support for navigation thru the dropdown items and select/deselect them.

**Comment by arzoum** [comment]
+1

**Comment by richrd** [comment]
+1

**Comment by pkempenaers** [comment]
Just to inform you guys: I've implemented this at my fork. You can see a demo of it in action [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/) (last 2 examples)

**Comment by pkempenaers** [comment]
And now also on this repo
