### ISSUE TITLE
Pre-select issue for selectionLimit 1

### ISSUE THREAD

**Issue by sali1982** [dotansimha/angularjs-dropdown-multiselect#151]
Did you know it is not possible to preselect when limit is 1?
See:
$scope.assetModel = [{id:"1"}];

$scope.assetSetting = {
selectionLimit: 1
}

It won't work, unless I change the selectionLimit to more than 1.

I noticed after selecting an asset by user, the assetModal is like this:
[id:"1"]

It is not an object. and it is not possible to set the modal like that!
What needs to be done to fix this???

**Comment by MorleyMinde** [comment]
I encountered the same problem today. To preselect when limit is 1 set the selected model as an object not array:

$scope.assetModel = {id:"1"};

Worked fine for me
