### ISSUE TITLE
One ng-dropdown-multiselect drop down open - click on another first does not close. Even with closeOnBlur: true 

### ISSUE THREAD

**Issue by philipfwilson** [dotansimha/angularjs-dropdown-multiselect#153]
## First off. Great tool !!!!

One ng-dropdown-multiselect drop down open - click on another first does not close. Even with closeOnBlur: true 

After you click on a checkbox in second dropdown the first dropdown will close. 

Thanks
Phil

**Comment by Ashviniv** [comment]
@philipfwilson I tried with two ng-dropdown-multiselect buttons.But I am not getting such issue.It is working perfectly fine.And even I didnot require closeOnBlur: true. You can check it on plunkr.If you are doing something different please let me know.
**plunkr:**
[http://plnkr.co/edit/yv9sUri2zXb5YYryLvQ3?p=preview](http://plnkr.co/edit/yv9sUri2zXb5YYryLvQ3?p=preview)

**Comment by shubhamsinghal** [comment]
ng-dropdown-multiselect does not closing on tab out however it is closing when I am clicking outside.
I want to close dropdown on tab-out also. Please help!
