### ISSUE TITLE
Both parent and subcategory selection possibilities

### ISSUE THREAD

**Issue by boboci9** [dotansimha/angularjs-dropdown-multiselect#154]
Hi, 
Great work the package is well documented, and has a very nice functionality.

I was wondering if there is a possibility when group items by properties is used to make the properties selectable as well. I am trying to achieve a multi selection dropdown for categories and their subcategories, and it should be possible to select either a some of the main  categories or some of the subcategories but the titles/main categories ( which you use as properties in the example) should be selectable as well.
Is this possible with your package?

Thank you for your help.

**Comment by pkempenaers** [comment]
I'm currently implementing an tree selection component over [here](https://github.com/pkempenaers/angularjs-dropdown-tree)
