### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DeanPoulin** [dotansimha/angularjs-dropdown-multiselect#159]
Thanks for open sourcing this directive.

I just noticed that this product does not have a license specified and therefore must be considered "All Rights Reserved" and not allowed.

Can you specify a license for this so that I can include this inside a project we've built. Something like AngularJS' license: https://github.com/angular/angular.js/blob/master/LICENSE?

I noticed that the bower.json includes the specification of the license as MIT. Just want to make sure to clearly specify the license somewhere so our corporate licensing can explicitly verify.

**Comment by rvalbuena-tc** [comment]
I'm also looking for license verification. So since the bower.json specifies MIT license, is that definitive license for this directive?

**Comment by pkempenaers** [comment]
It's MIT
