### ISSUE TITLE
Default selection does not work when selectionLimit:1

### ISSUE THREAD

**Issue by abhisheksimion** [dotansimha/angularjs-dropdown-multiselect#163]
I am using pre selected item and defining a limit for selection using <code>selectionLimit:1</code>, but this does not work. Here is plunkr link http://plnkr.co/edit/zEj6SLH9CPD0EtXNx27q?p=preview

**Comment by Ashviniv** [comment]
**@abhisheksimion** You need to set **selected model** to an object  **not** an  **array** of objects to work with selctionLimit: 1
i.e in your example set :
 ```javascript  
$scope.example65model = {id: 1};
```

**Comment by abhisheksimion** [comment]
@Ashviniv In your plunkr link too it is not able to have a default selection of 1 when `selectionLimit: 1`

Your plunkr link:
[http://plnkr.co/edit/Tg6y1PaR3yvZywyjRISP?p=preview](http://plnkr.co/edit/Tg6y1PaR3yvZywyjRISP?p=preview)

**Comment by pkempenaers** [comment]
Hi guys just for your information on my fork this is working as you can see in [my plunker](http://plnkr.co/edit/4KljCjWfJDaoomqt4SDY?p=preview) even without using lodash

You can find documentation for my fork [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/) and the repo [here](https://github.com/myforce/angularjs-dropdown-multiselect)
