### ISSUE TITLE
Iterating the input & output for object

### ISSUE THREAD

**Issue by selvarajpalani** [dotansimha/angularjs-dropdown-multiselect#168]
Is it possible to use the object for multiselect ['a','b','c','d'] instead of [{id:'a'},{id:'b'},{id:'c'},{id:'d'}].
for single select ['a'] instead of [{id:'a'}]. Because this will help us to avoid in adding and removing the instance 'id' everywhere.
I feel this is the only thing missed in the dropdown feature. Thanks.

**Comment by smileisak** [comment]
+1

**Comment by pkempenaers** [comment]
This is now possible in 2.0.0-beta.2
