### ISSUE TITLE
Disable & Clear feature

### ISSUE THREAD

**Issue by selvarajpalani** [dotansimha/angularjs-dropdown-multiselect#169]
Is it possible to  disable & clear the dropdowns?

**Comment by Ashviniv** [comment]
There no such option at the moment.But, here is the PR[#189](https://github.com/dotansimha/angularjs-dropdown-multiselect/pull/189) to add disable dropdown functionality along with example and documentation changes.

**Comment by pkempenaers** [comment]
disabled has beend added, clearing can be done by clearing your selectedModel array
