### ISSUE TITLE
onSelectItem fires when selectAll happens

### ISSUE THREAD

**Issue by sali1982** [dotansimha/angularjs-dropdown-multiselect#172]
How I can prevent the function for select one item from happening when select all happens? This has 100s of records and I do not want runs my select item function?

**Comment by roshanhadal** [comment]
I second this issue. Also I am experiencing issue with event not firing when 'onUnselectAll'.

**Comment by gauravg418** [comment]
I am also facing this problem. "onItemSelect" gets fires for all the items in the multi-select when i choose selectAll.  This is an emergency for me, anybody please provide the solution ASAP. Your effort will be appreciated. Thanks

**Comment by rhgithub1** [comment]
Same here. I went ahead and almost implemented lot of code. I cannot pick another plugin. Help to resolve this issue will be much appreciated.

**Comment by gauravg418** [comment]
I have solved this problem by doing some changes in multiselect js file. Find and replace below given function in original multiselect js and then check-

 $scope.selectAll = function () {
                    $scope.deselectAll(false);
                    $scope.externalEvents.onSelectAll();

                    angular.forEach($scope.options, function (value) {
                        $scope.setSelectedItem(value[$scope.settings.idProp], true,true);
                    });
                };

$scope.setSelectedItem = function (id, dontRemove, sendEvent) {
                    var findObj = getFindObj(id);
                    var finalObj = null;

                    if ($scope.settings.externalIdProp === '') {
                        finalObj = _.find($scope.options, findObj);
                    } else {
                        finalObj = findObj;
                    }

                    if ($scope.singleSelection) {
                        clearObject($scope.selectedModel);
                        angular.extend($scope.selectedModel, finalObj);
                        $scope.externalEvents.onItemSelect(finalObj);
                        if ($scope.settings.closeOnSelect) $scope.open = false;

                        return;
                    }

                    dontRemove = dontRemove || false;

                    var exists = _.findIndex($scope.selectedModel, findObj) !== -1;

                    if (!dontRemove && exists) {
                        $scope.selectedModel.splice(_.findIndex($scope.selectedModel, findObj), 1);
                        if (sendEvent != true)
                            $scope.externalEvents.onItemDeselect(findObj);
                    } else if (!exists && ($scope.settings.selectionLimit === 0 || $scope.selectedModel.length < $scope.settings.selectionLimit)) {
                        $scope.selectedModel.push(finalObj);
                        if (sendEvent != true)
                            $scope.externalEvents.onItemSelect(finalObj);
                    }
                    if ($scope.settings.closeOnSelect) $scope.open = false;
                };

**Comment by rhgithub1** [comment]
Thanks a lot. This worked great!

**Comment by rhgithub1** [comment]
just realized that the selectAll is getting invoked twice. Appreciate your help in advance.

**Comment by randanunn** [comment]
most aggravating 2 hours ever till this.  thank you @gauravg418!

**Comment by vojtechruz** [comment]
@dotansimha , It seems that there is already a pull request addressing this issue. Would you be so kind as to check it please? It would help us a lot. Thanks :)
