### ISSUE TITLE
How to hide scroll bars?

### ISSUE THREAD

**Issue by shlomogoldstein** [dotansimha/angularjs-dropdown-multiselect#177]
It says by default scroll bars are hidden, but they are not.....................

Using 

```
extra-settings="{scrollable:false}"
```
does not work either, or it is not clear how to use that.

So, how to a) hide scrollbars completely, b) show scrollbars if needed (auto) ?

**Comment by Midako** [comment]
The extra-settings
```javascript
extra-settings="{scrollable:false}"
```

will set scrollable to true and activate the possiblity to set a scrollableHeight

```
height : settings.scrollable ? settings.scrollableHeight : \'auto\' 
```

2  easy ways you go change it.

* You can expand your own css file.
```
.multiselect-parent .dropdown-menu {
    overflow: auto;
}
```

* You can change the directive itself.
```
<ul class="dropdown-menu dropdown-menu-form" ng-style="{display: open ? \'block\' : \'none\', height : settings.scrollable ? settings.scrollableHeight : \'auto\' }" style="overflow: scroll" >
```

the settings object will be extended so you can do something like
extra-settings="{scrollbar: 'hidden'}"

and change the template to
```
<ul class="dropdown-menu dropdown-menu-form" ng-style="{display: open ? \'block\' : \'none\', height : settings.scrollable ? settings.scrollableHeight : \'auto\', overflow: scrollbar ? \'scrollbar\' : \'auto\'}" style="overflow: scroll" >
```

**Comment by Hansel03** [comment]
An outstanding fix Midako, thank you very much.  Built my own css file 
`.multiselect-parent .dropdown-menu {
    overflow: auto;
}`

**Comment by shlomogoldstein** [comment]
Thank you for the answer.
