### ISSUE TITLE
How to make an element full width?

### ISSUE THREAD

**Issue by murilozilli** [dotansimha/angularjs-dropdown-multiselect#181]
Is there any configuration I can use to change the width of the button to be the same of the list when I open the option's list?

**Comment by leap0ffaith** [comment]
Did you solve the issue? I cannot find any way to make the width 100%.

**Comment by murilozilli** [comment]
@leap0ffaith I can't remember right now as this was 2 years ago. If I closed it probably I was able to make a workaround.
