### ISSUE TITLE
events - Triggering all time

### ISSUE THREAD

**Issue by jjayaraman** [dotansimha/angularjs-dropdown-multiselect#182]
Hi Team

Thanks for the wonderful Angular dropdown-multiselect component.

I am trying to use the events - onItemSelect() &  onItemDeSelect() but the events keeps triggering when I click any where instead of just the drop down.

I have also raised a stackoverflow issue.

http://stackoverflow.com/questions/34139031/dropdown-multiselect-events-triggering-all-time

Thanks

**Comment by Ashviniv** [comment]
@jjayaraman  You have called both the events at the same time using ```events="onItemSelect(example1model); onItemDeselect(example1model)" ```.Therefore both the events are getting triggered.To use these events you should declare $scope variable which will store both the events like shown below.And use this variable in html events attribute.
**Javascript**
```javascript
var jayApp = angular.module('jayApp',['angularjs-dropdown-multiselect']);

jayApp.controller('jayController', function($scope) {

	$scope.example1model = []; 
	$scope.example1data = [ {id: 1, label: "David"}, {id: 2, label: "Jhon"}, {id: 3, label: "Danny"}];
	
	
	// MultiSelect Drop down select - Event
	$scope.selecEvents = {
      onItemSelect: function(property) {
        console.log('select > ' +property);
  	  },
	
	  onItemDeselect: function(property) {
        console.log('deselect : ' +property);
	  }
	}
})
```
**HTML**
```html
<div ng-dropdown-multiselect="" options="example1data" selected-model="example1model" events="selectEvents">
```
