### ISSUE TITLE
A typo error in the documentation, section "onUnselectAll" on Events

### ISSUE THREAD

**Issue by jeffrey-effendy** [dotansimha/angularjs-dropdown-multiselect#186]
Can you please change the documentation on the "onUnselectAll" to "onDeselectAll"? Somewhat i got mine working with "onDeselectAll".

**Comment by Ashviniv** [comment]
@jeffrey-effendy  I have already sent the PR[#150](https://github.com/dotansimha/angularjs-dropdown-multiselect/pull/150) to change the documentation

**Comment by pkempenaers** [comment]
Hi,

I'm actively maintaining this component on my fork which you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect). You can install it using `bower install myforce-angularjs-dropdown-multiselect`, if you have an issue you may also create it at my fork.

I've updated the documentation to mention onDeselectAll. The documentation for my fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)
