### ISSUE TITLE
Undeclared variable "staticPath" in app.js

### ISSUE THREAD

**Issue by HokiePedro** [dotansimha/angularjs-dropdown-multiselect#188]

**Comment by Ashviniv** [comment]
@HokiePedro It is declared in development_index.html file here is the [line](https://github.com/dotansimha/angularjs-dropdown-multiselect/blob/8f751d841829597e40a93839d6db30305e92cc49/development_index.html#L12).

**Comment by HokiePedro** [comment]
Oh, thanks, I completely missed that.
