### ISSUE TITLE
Deselect all does not trigger onItemDeselect events

### ISSUE THREAD

**Issue by jvorcak** [dotansimha/angularjs-dropdown-multiselect#19]
Hi,

I've installed "angularjs-dropdown-multiselect": "~1.5.0" and I found out an issue in the code.
If you click on `Check all` button, onItemSelect event is triggered per each item in the model.
If you click on `Uncheck All`, I'd expect onItemDeselect event to be triggered per each item.

I'm aware of onSelectAll/onDeselectAll events, I just think that `Check all`/`Uncheck all` should behave in the same way.

$scope.events = {
      onItemSelect: function(item) {
        return $log.warn("" + item + " selected"); // is triggered per each item on `Check all`
      },
      onItemDeselect: function(item) {
        return $log.warn("" + item + " deselected"); // not triggered on `Uncheck all`
      }
    };

Hope this will help somebody.

**Comment by pkempenaers** [comment]
onItemDeselect should not fire on uncheckAll,
onItemSelect should not fire on checkAll
This is the behaviour right now as shown in [this plunker](http://plnkr.co/edit/GWNlJl?p=preview)
