### ISSUE TITLE
Chrome issue

### ISSUE THREAD

**Issue by Esadhanadevi** [dotansimha/angularjs-dropdown-multiselect#191]
This is working fine in firefox.In chrome and chromium the ul list is updating with values but not opening the dropdown list.And also i noticed the style(position,width & height) is not applying for class(dropdown-menu dropdown-menu-form).

**Comment by Ashviniv** [comment]
@Esadhanadevi  Can you provide example which you are trying?. Because , I am using dropdown multiselect on chrome. It's working perfectly fine.
