### ISSUE TITLE
disable some options into select

### ISSUE THREAD

**Issue by giovannyquin** [dotansimha/angularjs-dropdown-multiselect#192]
could you add some function to allow that some options are enable or disable to continue with click or other events.

For example

$scope.example16data = 
[ 
   {id: 1, label: "David", enable: true}, 
   {id: 2, label: "Jhon", enable: false}, 
   {id: 3, label: "Danny", enable: true}
];

According this object i can enable or disable these options, i want to clarify that the options are always visible, only change the styles and functionality, the disabled options won't permit click event

**Comment by Ashviniv** [comment]
@giovannyquin There is a PR  #189 available for this feature you can refer these changes in your fork. Or  you can refer [http://myforce.github.io/angularjs-dropdown-multiselect/#/](http://myforce.github.io/angularjs-dropdown-multiselect/#/). This includes some more advanced features for angular dropdown multiselect.

**Comment by pkempenaers** [comment]
And now also in this version
