### ISSUE TITLE
List linked

### ISSUE THREAD

**Issue by fsebbah** [dotansimha/angularjs-dropdown-multiselect#194]
Hi 
I have 2 dropdown. dropdown 1 and dropdown 2.
I would like generate the items of the dropdown 2 in function of the items selected in the dropdown 1.
I don't know how I can build this.
If you can help me,
Thanks.
Franck

**Comment by Ashviniv** [comment]
@fsebbah You can set options for dropdown2 onselect event of one item from first dropdown. I have attached example how you can set dropdown2 on selection of dropdown1.
**Plunkr:**
[http://plnkr.co/edit/DfGN12QPHLjqaD4UgF2D?p=preview](http://plnkr.co/edit/DfGN12QPHLjqaD4UgF2D?p=preview)

**Comment by fsebbah** [comment]
Hi Ashviniv,
Thanks for you example and for AngularJS Dropdown Multiselect.
Can you say if it's possible to apply css style ?
Thanks,
Franck

**Comment by Ashviniv** [comment]
@fsebbah Yes you can apply css style to multiselect dropdown. You just have to add ```buttonClasses: "btn btn-success"``` or any style you want to add in the settings attribute. 
I have updated the above plunkr with css style applied on it.
