### ISSUE TITLE
select-all as a toggle button

### ISSUE THREAD

**Issue by mkhanal** [dotansimha/angularjs-dropdown-multiselect#2]
Make "select all" a toggle button to select and unselect all instead of two buttons using config to say so.

Also, the text for this button (all buttons) and its icon/checkbox should be configurable.

**Comment by PrasadBOL** [comment]
Hi ,

I am not seeing this feature (select-all as a toggle button)in API documentation. Can you please provide how we can make "Select ALL"  as toggle button.

Thanks,
Prasad
