### ISSUE TITLE
Is it possible to child options as well

### ISSUE THREAD

**Issue by selvarajpalani** [dotansimha/angularjs-dropdown-multiselect#200]
Hi, Is it possible to show child options as well?

Each drop down value will have child values as well, I need to show it in the next line. Is it possible. or can I need include html tag in the name attribute.

Please advice, thanks

**Comment by pkempenaers** [comment]
I'm implementing a tree-select over [here](https://github.com/pkempenaers/angularjs-dropdown-tree)
