### ISSUE TITLE
lodash 4.0.1 removed the _.contains alias

### ISSUE THREAD

**Issue by leoncarl** [dotansimha/angularjs-dropdown-multiselect#201]
In order to use the latest lodash you'll need to use _.includes instead of _.contains here:
https://github.com/dotansimha/angularjs-dropdown-multiselect/blob/master/src/angularjs-dropdown-multiselect.js#L155

The last version of lodash that still had the _.contains alias was v3.10.1

**Comment by CodyMorris** [comment]
Thanks for posting this @leoncarl

**Comment by hackel** [comment]
This is a really critical issue, can we get this PR merged?  Is anyone actively maintaining this project anymore?  There have been no updates for a year and a half...

**Comment by njj** [comment]
A quick (and extremely ugly) fix for this is:

```javascript
_.contains = _.includes;
```

**Comment by pkempenaers** [comment]
Hi I've removed all lodash dependencies at my fork which I'm actively maintaining and you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect). You can install it using `bower install myforce-angularjs-dropdown-multiselect`, if you have an issue you may also create it at my fork.

Documentation for my fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)
