### ISSUE TITLE
Does it work with Angular Material ?

### ISSUE THREAD

**Issue by ganeshghalame** [dotansimha/angularjs-dropdown-multiselect#203]
I am implementing UI using angular material, I wanted to add multi select drop-downs in my UI, I already used this with bootstrap, does it supports angular material ? if yes please provide any reference of the same.

**Comment by harshaldhake** [comment]
+1

**Comment by ganeshghalame** [comment]
@harshaldhake Now angular material have added multi select dropdown [https://material.angularjs.org/latest/demo/select](check here)
