### ISSUE TITLE
The event 'onUnselectAll' does not exist, the documentation is incorrect

### ISSUE THREAD

**Issue by lukfcb** [dotansimha/angularjs-dropdown-multiselect#205]
The correct name of the event is "onDeselectAll", please correct the documentation.

**Comment by gregRV** [comment]
Thanks for that, @lukfcb!

**Comment by randanunn** [comment]
thank you!

**Comment by dchambers** [comment]
Was just about to create an issue for this when I found this one. Would providing a pull-request make this get fixed sooner?

**Comment by jennyphan** [comment]
documentation still not updated, but I was able to find the answer here...

**Comment by pkempenaers** [comment]
Hi,

I'm actively maintaining this component on my fork which you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect). You can install it using `bower install myforce-angularjs-dropdown-multiselect`, if you have an issue you may also create it at my fork.

I've updated the documentation to mention onDeselectAll. The documentation for my fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)

**Comment by dchambers** [comment]
Hey, great work @pkempenaers, and I see that you're now 85 commits ahead of the original project! 👏 

Is it worth mentioning on your `README.md` that this fork contains fixes and features not in the original repository, which appears to have been abandoned?

**Comment by pkempenaers** [comment]
And now everything is back in this repo
