### ISSUE TITLE
Cannot read property  'push' of undefined TypeError: Cannot read property 'push' of undefined  at Scope.$scope.setSelectedItem (angularjs-dropdown-multiselect.js:277)

### ISSUE THREAD

**Issue by hasmukh** [dotansimha/angularjs-dropdown-multiselect#209]
When I click on check box the below error comes 

`TypeError: Cannot read property 'push' of undefined
    at Scope.$scope.setSelectedItem (angularjs-dropdown-multiselect.js:277)
    at angular.js:10288
    at angular.js:18086
    at Scope.$eval (angular.js:12045)
    at Scope.$apply (angular.js:12145)
    at HTMLAnchorElement.<anonymous> (angular.js:18085)
    at HTMLAnchorElement.n.event.dispatch (jquery.min.js:3)
    at HTMLAnchorElement.r.handle (jquery.min.js:3)`

Can someone please tell me what is the mistake here ?

![2016-02-11_12h07_39](https://cloud.githubusercontent.com/assets/659190/12970931/e7e5f536-d094-11e5-9fa1-ff41059f1e5a.png)

**Comment by shubhamsinghal** [comment]
I think you are using "ng-modal" instead of "selected-model" in your HTML.

**Comment by vknaveenkumar** [comment]
Any solution for this ?

**Comment by praveenuics** [comment]
I am stuck at this error as well, can someone please help on this issue?

**Comment by hasmukh** [comment]
How can it be closed I dont understand ? We still need help on that.

**Comment by saurabhsumansp7** [comment]
TypeError: Cannot read property 'push' of undefined.......
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AngularforEach</title>
    <script src="scripts/angular.js"></script>
    <script>
        var app=angular.module('DemoApp',[]);
        app.controller('HomeController',function ($scope) {
            var products=[
                {Name:'Tv',Price:120000},
                {Name:'shoe',Price:4500}
            ];
            $scope.productName=[];
            angular.forEach(products,function (values,keys) {
                $scope.productNames.push(values.Name);
            })
        })
    </script>
</head>
<body ng-app="DemoApp" ng-controller="HomeController">
<div>
    <h2>Products</h2>
    <li ng-repeat="item in product Name">{{item}}</li>
</div>
</body>
</html>
