### ISSUE TITLE
Can I tie two selections?

### ISSUE THREAD

**Issue by axewelder** [dotansimha/angularjs-dropdown-multiselect#21]
I use angularjs-dropdown-multiselect to let the user specify how much or how little of their tabular data they see; I let them select/de-select available columns/fields and show/hide them accordingly.  The labels in the dropdown array match the data field elements of the array, so selecting a choice (col3 for example) enables the visibility of a data field by the same name (col3 in this example).
  Two of the columns however _should_ be shown/hidden together.  If the user selects col4, I would like both col4 and col5 to appear.  If the user deselects col5, I would like both col4 and col5 to be hidden.  Alternatively, I could use a single dropdown choice, perhaps called col4/col5, that shows/hides col4 and col5 together.
  How would I go about doing either of these?

Thanks

**Comment by pkempenaers** [comment]
I do think that this is something that could be implemented as a new feature.
If you still want this could you pleas answer before 2017/02/01. Otherwise I'll close this issue
