### ISSUE TITLE
"onItemSelect" event fires for all items when "onSelectAll" is selected.

### ISSUE THREAD

**Issue by gauravg418** [dotansimha/angularjs-dropdown-multiselect#211]
"onItemSelect" gets fires for all the items in the multi-select when i choose selectAll. Please provide any solution to avoid this. Your effort will be appreciated. Thanks

Edit: I solved it by hacking the js and passing a sendEvent paramter in onSelectedItem from selctAll function.
$scope.setSelectedItem = function (id, dontRemove, sendEvent) {
 if (sendEvent != true)
                            $scope.externalEvents.onItemDeselect(findObj);
}

**Comment by rameshkondapallinektan** [comment]
no working this please provide if any tricks
