### ISSUE TITLE
feature request: dropdown inside dropdown

### ISSUE THREAD

**Issue by xmsalman** [dotansimha/angularjs-dropdown-multiselect#216]
can you add a feature for the dropdown to show following response.

```
[
  {
    "id": 8,
    "label": "AA",
    "items": [
      {
        "id": 9,
        "label": "BB",
        "items": [
          {
            "id": 10,
            "label": "DD",
            "items": []
          }
        ]
      },
      {
        "id": 11,
        "label": "CC",
        "items": []
      }
    ]
  }
]
```

AA will be dropdown with child BB. BB will also be a dropdown with child DD.
Im new to angularjs. Please excuse if there is something wrong

**Comment by pkempenaers** [comment]
I'm implementing a treeview select component over [here](https://github.com/pkempenaers/angularjs-dropdown-tree)
