### ISSUE TITLE
Error when I try to use example: in $scope.getButtonText

### ISSUE THREAD

**Issue by tenaz3** [dotansimha/angularjs-dropdown-multiselect#22]
Console Error :

```
Error: [$interpolate:interr] Can't interpolate: {{getButtonText()}} 
TypeError: Cannot read property 'length' of undefined
http://errors.angularjs.org/1.2.19/$interpolate/interr?p0=%7B%7BgetButtonTe…%A0&p1=TypeError%3A%20Cannot%20read%20property%20'length'%20of%20undefined
    at http://0.0.0.0:9000/bower_components/angular/angular.js:78:12
    at Object.$interpolate.fn (http://0.0.0.0:9000/bower_components/angular/angular.js:8756:26)
    at Scope.$digest (http://0.0.0.0:9000/bower_components/angular/angular.js:12426:40)
    at Scope.$apply (http://0.0.0.0:9000/bower_components/angular/angular.js:12699:24)
    at done (http://0.0.0.0:9000/bower_components/angular/angular.js:8287:45)
    at completeRequest (http://0.0.0.0:9000/bower_components/angular/angular.js:8499:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://0.0.0.0:9000/bower_components/angular/angular.js:8438:11) angular.js:9959
```

HTML:

```
<div ng-dropdown-multiselect="" options="example1data" selected-model="example1model"></div>
```

JS:

```
$scope.example1model = []; $scope.example1data = [ {id: 1, label: "David"}, {id: 2, label: "Jhon"}, {id: 3, label: "Danny"}];
```

**Comment by karthilxg** [comment]
I'm getting the same error even after loading the lodash, when I debugged it I found that the 'ngDropdownMultiselect' directive is getting executed before the scope binding, so the $scope.selectedModel is undefined at that time, calling length on undefind is causing this issue.

Adding an undefined check is resolving this issue,

if ($scope.settings.dynamicTitle && $scope.selectedModel && ($scope.selectedModel.length > 0 || (angular.isObject($scope.selectedModel) && _.keys($scope.selectedModel).length > 0))) {

 Error: [$interpolate:interr] Can't interpolate: {{getButtonText()}} 
TypeError: Cannot read property 'length' of undefined
http://errors.angularjs.org/1.2.28/$interpolate/interr?p0=%7B%7BgetButtonText()%7D%7D%C2%A0&p1=TypeError%3A%20Cannot%20read%20property%20'length'undefinedf%20undefined
    at VALIDITY_STATE_PROPERTY (http://localhost:9000/bower_components/angular/angular.js:78:12)
    at Object.$get.fn (http://localhost:9000/bower_components/angular/angular.js:8921:26)
    at Scope.$get.Scope.$digest (http://localhost:9000/bower_components/angular/angular.js:12642:40)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1468:23)
    at Scope.$get.Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:12915:24)
    at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1478:22)
    at done (http://localhost:9000/bower_components/angular/angular.js:8450:45)
    at completeRequest (http://localhost:9000/bower_components/angular/angular.js:8664:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:9000/bower_components/angular/angular.js:8603:11)

**Comment by karthilxg** [comment]
https://github.com/dotansimha/angularjs-dropdown-multiselect/pull/60

**Comment by online4sam** [comment]
Getting the below console error.

[Error] undefined undefined
	(anonymous function) (angular.js, line 10103)
	errorCatcherHandler (errorCatcher.js, line 11)
	fn (angular.js, line 8900)
	$digest (angular.js, line 12619)
	$apply (angular.js, line 12892)
	done (angular.js, line 8427)
	completeRequest (angular.js, line 8641)
	onreadystatechange (angular.js, line 8580)
[Error] $digest@http://localhost:9000/bower_components/angular/angular.js:12669:39
$apply@http://localhost:9000/bower_components/angular/angular.js:12892:31
done@http://localhost:9000/bower_components/angular/angular.js:8427:51
completeRequest@http://localhost:9000/bower_components/angular/angular.js:8641:15
onreadystatechange@http://localhost:9000/bower_components/angular/angular.js:8580:26 undefined
	(anonymous function) (angular.js, line 10103)
	errorCatcherHandler (errorCatcher.js, line 11)
	$apply (angular.js, line 12894)
	done (angular.js, line 8427)
	completeRequest (angular.js, line 8641)
	onreadystatechange (angular.js, line 8580)
[Error] Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! (angular.js, line 12669)
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.2.27/$rootScope/infdig?p0=10&p1=%5B%5D

**Comment by online4sam** [comment]
I tried the fix of karthilxg and it is working for me.
Added the condition like below.
if ($scope.settings.dynamicTitle && $scope.selectedModel && ($scope.selectedModel.length > 0 || (angular.isObject($scope.selectedModel) && _.keys($scope.selectedModel).length > 0))) {

**Comment by srinu0681** [comment]
I am getting the same error. Where do we have to add this condition? Is it inside the angularjs-dropdown-multiselect.js ? 
I tried adding it inside the angularjs-dropdown-multiselect.js but getting another error like "$scope is not defined"
Please help.

**Comment by karthilxg** [comment]
@srinu0681 I have added the changes here https://github.com/dotansimha/angularjs-dropdown-multiselect/pull/60/files

**Comment by srinu0681** [comment]
It worked. Thank you @karthilxg

**Comment by ghadeerrahhal** [comment]
+1
Thank you @karthilxg

**Comment by cpoole** [comment]
+1 @karthilxg 
Thanks.

How has this not been merged in yet?!

**Comment by Bhavin305** [comment]
I have included lodash like this.
<script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/3.2.0/lodash.min.js"></script>
    <script>
      if (!window.jQuery.ui) {
        document.write('<script src="js/libs/lodash.min.js"><\/script>');
      }
    </script>
still getting Error: [$interpolate:interr] Can't interpolate: {{getButtonText()}} 
ReferenceError: _ is not defined.

**Comment by heathf** [comment]
Thanks for the info.  Adding lodash also fixed it for me.  It seems like that should be mentioned as a requirement.  If it is, I didn't see it. (although admittedly didn't go through the docs in their entirety)

**Comment by charsoft** [comment]
Thank you @karthilxg!!

**Comment by Bhavin305** [comment]
Define multi-selection module like this 
directiveModule.directive('ngDropdownMultiselect', ['$filter', '$document', '$compile', '$parse','_',
    function ($filter, $document, $compile, $parse,_)

or 

angularApp.run(['$rootScope', '_',
    function ($rootScope,_) {
        $rootScope._ = window._;

**Comment by Hansel03** [comment]
I tried the fix of karthilxg and it is working for me. 
I have replaced the file angularjs-dropdown-multiselect.js in the line 180 

+                    if ($scope.settings.dynamicTitle && $scope.selectedModel && ($scope.selectedModel.length > 0 || (angular.isObject($scope.selectedModel) && _.keys($scope.selectedModel).length > 0))) {


 and everything works properly

**Comment by chappers72** [comment]
An outstanding fix Hansel03, thank you very much.

**Comment by pboffino** [comment]
Yeah, but this way it uses the deault values for the texts and I need to use my own :/

**Comment by NeelaSundaram** [comment]
Thanks. Adding lodash script helped me.

**Comment by hansiemithun** [comment]
@here  -   Hi, i am facing similar issue. Recently download doesnt contain this change: https://github.com/dotansimha/angularjs-dropdown-multiselect/pull/60/files

Latest link: https://github.com/dotansimha/angularjs-dropdown-multiselect/blob/master/src/angularjs-dropdown-multiselect.js#L266

This gets fixed if the earlier code gets merged with the latest version. Also once this is fixed and when i try to update the record, it throws an error as below:
```

TypeError: collection.some is not a function
    at findIndex (app.vendor-.min.js:96899)
    at Scope.$scope.isChecked (app.vendor-.min.js:96716)
    at app.vendor-.min.js:96574
    at Object.forEach (app.vendor-.min.js:1208)
    at Scope.$scope.getButtonText (app.vendor-.min.js:96573)
    at fn (eval at compile (app.vendor-.min.js:16009), <anonymous>:4:230)
    at expressionInputWatch (app.vendor-.min.js:17137)
    at Scope.$digest (app.vendor-.min.js:18711)
    at Scope.$apply (app.vendor-.min.js:18985)
    at HTMLButtonElement.<anonymous> (app.vendor-.min.js:27
```

Also assist me how to have a quick fix if this is not merged at the earliest from controller?

**Comment by anita246** [comment]
I was getting same issue. I resolve it my correcting my array of options and initialised model as blank array.

$scope.studentModel = [];
$scope.students =  [{id: 1, label: "David"}, {id: 2, label: "Jhon"}, {id: 3, label: "Danny"}];

please check array should be in form $scope.students =  [{id: 1, label: "David"}, {id: 2, label: "Jhon"}, {id: 3, label: "Danny"}]; . In my case array was not in this form during traversing my label attribute was missing. So Check your array.
