### ISSUE TITLE
Feature request. HTML templates for list items

### ISSUE THREAD

**Issue by amit777** [dotansimha/angularjs-dropdown-multiselect#222]
It would be awesome if we could format the list items as we want. For example including small images or extra information rather than just the text attribute.

**Comment by dmartinho** [comment]
Maybe we should ask to a more recent fork maintened like : https://github.com/myforce/angularjs-dropdown-multiselect  . As they are doing here : https://github.com/dotansimha/angularjs-dropdown-multiselect/issues/212

**Comment by pkempenaers** [comment]
I've created an issue at my own fork for this feature. If you could leave a comment or a reaction over there so i know I should go ahead and implement it

**Comment by pkempenaers** [comment]
Hi guys I went ahead and implemented this for you on my own fork, a demo of it is available at [my demo page](http://myforce.github.io/angularjs-dropdown-multiselect/#/).

**Comment by pkempenaers** [comment]
And now here as well
