### ISSUE TITLE
How to use "strict" search with enableSearch setting?

### ISSUE THREAD

**Issue by anshul-budhiraja** [dotansimha/angularjs-dropdown-multiselect#225]
How can I use "strict" option with the search setting. I am looking for something similar to "Name Only" example at [Angular Filter](https://docs.angularjs.org/api/ng/filter/filter) page. 

Another example of what I want is, If you search for "ak" in the example [here](https://jsfiddle.net/michaeldeongreen/22et6sao/9/), result set should not have "Alaska" because it doesn't have the "ak" combination. It is in the result set because of its "Id" which "AK". Please suggest asap.

**Comment by pkempenaers** [comment]
Hi,

I've implemented something that lets you do this at my fork which I'm actively maintaining and you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect). You can install it using `bower install myforce-angularjs-dropdown-multiselect`, if you have an issue you may also create it at my fork.

You can specify the searchField as a setting, if you set it to 'label' the search will be applied on label only.

This is included from version 1.4.0.
Documentation for my fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)

**Comment by mohitgoel01** [comment]
+1
