### ISSUE TITLE
closeOnSelect and closeOnDeselect are not working in extra-settings

### ISSUE THREAD

**Issue by shrikantpatwari** [dotansimha/angularjs-dropdown-multiselect#226]
Hi

When I try to use `closeOnSelect` and `closeOnDeselect` I found that it is not working and when I explored the source code then I found that there is no any code written for this setting properties

**Comment by pkempenaers** [comment]
Hi I've fixed this at my fork which I'm actively maintaining and you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect). You can install it using `bower install myforce-angularjs-dropdown-multiselect`, if you have an issue you may also create it at my fork.

This fix is included in version 1.1.2, 1.2.2 and 1.3.2 (and higher)
Documentation for my fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)

**Comment by morow93** [comment]
@pkempenaers thank you for work you have done!
