### ISSUE TITLE
`onItemDeselect` fires before `options` are updated

### ISSUE THREAD

**Issue by dchambers** [dotansimha/angularjs-dropdown-multiselect#227]
Whereas `onItemSelect`, `onSelectAll` and `onUnselectAll` all fire after `items` has updated, allowing you to rely on the current state of the model, `onItemDeselect` fires before the model has updated, making it impossible to rely on the state of the model.

Although the different call-backs include parameters that allow you to know the current state, the model is much more convenient if you are happy to have a single effective `onchange` call-back, for example:

``` html
<ng-dropdown-multiselect options="tagOptions" selected-model="tagsModel"
 events="{onItemSelect: onChange, onItemDeselect: onChange, onSelectAll: onChange, onDeselectAll: onChange}">
</ng-dropdown-multiselect>
```

I've worked around the issue for the time being using a `setTimeout(0)`.

**Comment by pkempenaers** [comment]
This should be fixed by now
