### ISSUE TITLE
No means to style opened drop-down

### ISSUE THREAD

**Issue by dchambers** [dotansimha/angularjs-dropdown-multiselect#228]
I wanted to style the caret in the drop-down differently when the menu was open, so I changed this line:

``` js
template = '<div class="multiselect-parent btn-group dropdown-multiselect">';
```

to this:

``` js
template = '<div class="multiselect-parent btn-group dropdown-multiselect" ng-class="{\'dropdown-multiselect-open\': open}">';
```

which worked great, but maybe this should be incorporated into the main codebase?

**Comment by pkempenaers** [comment]
open is set on the root div in the current version
