### ISSUE TITLE
Display selected values in button

### ISSUE THREAD

**Issue by kumarabrol** [dotansimha/angularjs-dropdown-multiselect#233]
Currently when i select couple of values from the dropdown ,the total count of selected values starts showing in the button.Is it possible we can show selected values in the button text?

**Comment by pkempenaers** [comment]
set the extra-settings: smartButtonMaxItems to a number higher than 0, this will display the names of the selected items, when the amount of selected items is bigger than the specified number it'll add ,...

You can see this in action in this plunker:
https://plnkr.co/edit/RunG8LfMSI85Nb5hfC1I?p=preview

I'm maintaining this component on my own fork which you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect) and documentation of it [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/), feel free to make issues over at my repository.
