### ISSUE TITLE
onMaxSelectionReached event is Not firing

### ISSUE THREAD

**Issue by kpvnreddy** [dotansimha/angularjs-dropdown-multiselect#234]
$scope.propertyContactSetting = {
                selectionLimit: 2
}

 <div ng-dropdown-multiselect=""
                                                     options="row.contacts"
                                                     selected-model="row.contactArray"
                                                     extra-settings="propertyContactSetting"
                                                     checkboxes="true"
                                                     translation-texts="customDefaultText"
                                                     events="multiselectEvents"
                                                     class="btncaret">
                                                </div>

 $scope.multiselectEvents = {
                onMaxSelectionReached: function () {  // This event is not firing on selection of max limit
                    alert("you can not select more than 2 contacts");
                }
            };

**Comment by pkempenaers** [comment]
Hi,

There actually was no documentation for onMaxSelectionReached. (Something that happens more often on this component)

I've implemented this at my fork which I'm actively maintaining and you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect). You can install it using `bower install myforce-angularjs-dropdown-multiselect`, if you have an issue you may also create it at my fork.

You can see an example of it working [at this plunker](http://plnkr.co/edit/ID2DkRkQeLOkypisQuPG?p=preview)

This fix is included in version 1.1.5, 1.2.5 and 1.3.7 (and higher)
Documentation for my fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)

**Comment by BearandYoon** [comment]
Hi @pkempenaers 
I want to use myforce-angularjs-dropdown-multiselect component on my Meteor/AngularJs project.
So I need to install this component by using NPM.
Is this possible for me?

**Comment by BearandYoon** [comment]
Hi @pkempenaers 
I have resolved by myself.
Thanks.

**Comment by BearandYoon** [comment]
I am going to set the "selectionLimit" field of the extra-setting in run time.

$scope.organisationCount = 0;
        $scope.organisationSettings = {
            scrollableHeight: '200px',
            scrollable: true,
            enableSearch: false,
            externalIdProp: "id",
            showUncheckAll: false,
            selectionLimit: $scope.organisationCount
        };
.....

function getItems() {
       ....
       $scope.organisationCount = items.length;
}

Is this possible?

**Comment by pkempenaers** [comment]
We're working on this for v2 (#290)
