### ISSUE TITLE
cn language support?

### ISSUE THREAD

**Issue by gischina** [dotansimha/angularjs-dropdown-multiselect#237]
cn language support?

**Comment by pkempenaers** [comment]
You can use the text objects to specify translations, it has these properties.

checkAll
uncheckAll
selectionCount
selectionOf
searchPlaceholder
buttonDefaultText
dynamicButtonTextSuffix

I'm maintaining this repository on a separate fork which you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect), if you want quicker response you can create issues over there.

You can find the specification for the text at the bottom of [this page](http://myforce.github.io/angularjs-dropdown-multiselect/#/)
