### ISSUE TITLE
Mistake in documentation. onUnselectAll > onDeselectAll

### ISSUE THREAD

**Issue by adybionka** [dotansimha/angularjs-dropdown-multiselect#238]
In documentation is onUnselectAll, which doesn't work. I've checked in code and it is onDeselectAll. Please update documentation.

**Comment by pkempenaers** [comment]
Hi,

I'm actively maintaining this component on my fork which you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect). You can install it using `bower install myforce-angularjs-dropdown-multiselect`, if you have an issue you may also create it at my fork.

I've updated the documentation to mention onDeselectAll. The documentation for my fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)
