### ISSUE TITLE
feature request: Allowing disabled elements in the dropdown

### ISSUE THREAD

**Issue by jordidebarcelona** [dotansimha/angularjs-dropdown-multiselect#239]
Is there a way to mark some of the 'options' of the dropdown as 'disabled' so that can be viewed but no selected?
This is usefull when using dropdowns placed side by side, and you want that once an option is selected in one of them it is seen as disabled in the others.

**Comment by pkempenaers** [comment]
Hi,

I've implemented something like this at my fork which I'm actively maintaining and you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect). You can install it using `bower install myforce-angularjs-dropdown-multiselect`, if you have an issue you may also create it at my fork.

Setting the field "disabled" of an option to true will disable that option, if the option was previously checked it will still stay checked and will not be able to be unchecked.

This is included from version 1.8.0.
Documentation for my fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)
