### ISSUE TITLE
Multi Nested Grouping

### ISSUE THREAD

**Issue by kevinsoltis41** [dotansimha/angularjs-dropdown-multiselect#240]
I'm trying to see if there was an easy way to have multiple levels with your group nesting?

data: [{ name: 'Jim', age: 10, gender: 'M'}, { name: 'Joe', age: 20, gender: 'M'}, 
{ name: 'Jill', age: 10, gender: 'M'}, { name: 'Mary', age: 20, gender: 'M'}];

DDL:
- Male
  - Age > 10
    - Render Joe & all others
  - Age <= 10
    - Render Jim & all  others
  - Female etc...

Thank You in advance,
Kevin Soltis

**Comment by pkempenaers** [comment]
I'm implementing a similar component [here](https://github.com/pkempenaers/angularjs-dropdown-tree)
