### ISSUE TITLE
_.contains is not a function

### ISSUE THREAD

**Issue by phuwin** [dotansimha/angularjs-dropdown-multiselect#241]
`_.contains is not a function`
I think because of the new **lodash** version, they change `contains` into  `includes`. I replace all `contains` into  `includes`and it works now.

**Comment by itsanmax** [comment]
@phuwin : Is it a good idea to change `contains` into `includes` directly in plugin? Because we're suppose to use it through bower and in case there will be any change/ update in this plugin our local changes will be gone. Please suggest.

**Comment by pkempenaers** [comment]
Hi guys I've fixed this and some other things on a fork (for example no more lodash dependency) and i'm actively maintaining it.
You can install that fork using
`bower install myforce-angularjs-dropdown-multiselect`

The documentation for that specific fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/). and the fork itself [here](https://github.com/myforce/angularjs-dropdown-multiselect)

**Comment by itsanmax** [comment]
Thanks @pkempenaers . Trying to use this one and in case of any issue will let you know.

**Comment by phuwin** [comment]
@itsanmax I don't use bower so as long as it works, it's fine for me :D

**Comment by babilog** [comment]
I think this is certainly an issue that needs to be acknowledged, caused quite a few head aches.

**Comment by pkempenaers** [comment]
@babilog this repo isn't being maintained at all for the moment (the reason why I've forked it and have been maintaining it myself as you can read in my previous comment)

**Comment by babilog** [comment]
@pkempenaers no problem then, thanks for letting me know!

**Comment by mandarsawant** [comment]
Hello all i am still facing an issue with the same error. Any updates or solutions will be helpful.

**Comment by sreekanth-karini** [comment]
Hi, In the latest version(4.0.0) of lodash, _.contais() method is not defined. It was available in version "3.10.0". So we need to update " _.contains " with " _.includes " in plugin itself then it works fine TQ.
