### ISSUE TITLE
Feature Request : Allowing to show more items in list along with lable in the dropdown

### ISSUE THREAD

**Issue by dnyaneshwaruttarwar** [dotansimha/angularjs-dropdown-multiselect#244]
Hi I want to display more properties to dropdown list along with label. If their is feature that will show more properties that will be a good functionality.

thanks for your help

**Comment by Ashviniv** [comment]
@dnyaneshwaruttarwar You can achieve this by `group-by` property of `Angular dropdown multiselect`
*Example:* 
 ```
<div ng-dropdown-multiselect="" options="example11data" selected-model="example11model" extra-settings="example11settings" group-by="gender"></div>
```
```
// JavaScript
 $scope.example11model = []; $scope.example11data = [ {id: 1, label: "David", gender: 'M'}, {id: 2, label: "Jhon", gender: 'M'}, {id: 3, label: "Lisa", gender: 'F'}, {id: 4, label: "Nicole", gender: 'F'}, {id: 5, label: "Danny", gender: 'M'}]; $scope.example11settings = { groupByTextProvider: function(groupValue) { if (groupValue === 'M') { return 'Male'; } else { return 'Female'; } } };
```
Working example is with explaination available on  [ Group Items By Property](http://myforce.github.io/angularjs-dropdown-multiselect/#/).

**Comment by pkempenaers** [comment]
You can also use the new template setting (default is {{option.name}})
