### ISSUE TITLE
Can we add a event like onSelectChanged or onDropdownListClosed?  I have given the code example, please check that.

### ISSUE THREAD

**Issue by athenaxing** [dotansimha/angularjs-dropdown-multiselect#246]
In my projects, I have many multiselect controls in one page.  I have to distinguish each controls with a tag. And save the values automatically when the value has been changed.

scope: {
                selectedModel: '=',
                options: '=',
                extraSettings: '=',
                events: '=',
                searchFilter: '=?',
                translationTexts: '=',
                groupBy: '@',
                tag:'=',    // this is for an object that need to parse to the onSelectChanged event
            },

$scope.externalEvents = {
                    onItemSelect: angular.noop,
                    onItemDeselect: angular.noop,
                    onSelectAll: angular.noop,
                    onDeselectAll: angular.noop,
                    onInitDone: angular.noop,
                    onMaxSelectionReached: angular.noop,
                    onSelectChanged:angular.noop,  //add the event here
                };

 $scope.toggleDropdown = function () {
                    $scope.open = !$scope.open;
                    if (!$scope.open){
                      $scope.externalEvents.onSelectChanged($scope.tag);  //when the dropdown list     closed, fire this event.
                    }
                };

Or we can add an event onDropdownListClosed, User can change the value outside the control, but still an tag object need to be passed in for the future using.

**Comment by pkempenaers** [comment]
Hi @athenaxing I've been maintaining this repo on my own fork [here] (https://github.com/myforce/angularjs-dropdown-multiselect) This is one of the multiple features that have been added by me.
