### ISSUE TITLE
Selecting "onSelectAll" fires "onItemSelect" n number of times

### ISSUE THREAD

**Issue by vishnuvg1984** [dotansimha/angularjs-dropdown-multiselect#248]
The "onSelectAll()" event implementation is buggy. On clicking "Select All " it will trigger "onSelectAll" event along with a n number of times the "onItemSelect" event as well . If the user clicking "OnSelectAll" there is no need to trigger again the "onItemSelect" multiple times.

**Comment by pkempenaers** [comment]
Hi I've fixed this at my fork which I'm actively maintaining and you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect). I've also added a lot of extra features. You can install it using `bower install myforce-angularjs-dropdown-multiselect`, if you have an issue you may also create it at my fork.

Documentation for my fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)

**Comment by vishnuvg1984** [comment]
Oh thanks. I will check it.

**Comment by vishnuvg1984** [comment]
Yes the issue got fixed in your fork. Thanks a lot.

**Comment by mockpit** [comment]
Also having this issue using the myforce fork. Clicking select all triggers onItemSelect for each object in the dropdown.

**Comment by pkempenaers** [comment]
This seems to be fixed
