### ISSUE TITLE
onUnselectAll() event wont trigger when clicking "uncheckAll"

### ISSUE THREAD

**Issue by vishnuvg1984** [dotansimha/angularjs-dropdown-multiselect#249]
On clicking the uncheckAll button it is observed that the checkboxes are getting cleared but the onUnselectAll() event is not getting fired at all.

**Comment by pkempenaers** [comment]
(Same comment as the other issue :wink: )

Hi I've fixed this at my fork which I'm actively maintaining and you can find [here](https://github.com/myforce/angularjs-dropdown-multiselect). You can install it using `bower install myforce-angularjs-dropdown-multiselect`, if you have an issue you may also create it at my fork.

Documentation for my fork can be found [here](http://myforce.github.io/angularjs-dropdown-multiselect/#/)

**Comment by vishnuvg1984** [comment]
Thanks a lot , will check it.

**Comment by vishnuvg1984** [comment]
Yes the issue got fixed in your fork. Thanks a lot.

**Comment by Adriengaio** [comment]
onUnselectAll wrote in the docs do not correspond with the onDeselectAll externalEvents in the library
  
.bower.json
 "version": "1.5.2",

**Comment by pkempenaers** [comment]
Documentation also updated to onDeselectAll
