### ISSUE TITLE
Implement closeOnSelect

### ISSUE THREAD

**Issue by mkdbns** [dotansimha/angularjs-dropdown-multiselect#25]
The option to closeOnSelect doesn't appear to be implemented in the current version.  I would love to activate that setting on my project. Could you implement it in the next version?

**Comment by MauritzKruger** [comment]
@dotansimha 

Can I request that this request be handled, see the merge did happen into src code, but dist code however does not have it. Can it be that merge happened into src, but not the build task?

**Comment by pkempenaers** [comment]
closeOnSelect has been implemented
