### ISSUE TITLE
extra-settings not honoring scope value

### ISSUE THREAD

**Issue by shonatodc** [dotansimha/angularjs-dropdown-multiselect#259]
I'm using the example from the website and the scope is not setting the values for the dropdown. I'm using AngularJS v1.5.8. 

plnkr: https://embed.plnkr.co/vuR0ZDL20gASvYLQZLdT/

**Comment by Ashviniv** [comment]
@shonatodc In your code you have not added `angularjs-dropdown-multi-select` directive for the example. 
I have just changed app initialization as follows and it is working for me.

`var app = angular.module('app', ['angularjs-dropdown-multiselect']);
`

You can refer this plunkr: 
[https://plnkr.co/edit/vuR0ZDL20gASvYLQZLdT?p=preview](https://plnkr.co/edit/vuR0ZDL20gASvYLQZLdT?p=preview)
