### ISSUE TITLE
New project's fork. Please help us

### ISSUE THREAD

**Issue by ygorlazaro** [dotansimha/angularjs-dropdown-multiselect#265]
Good morning,

I think this is a pretty good directive, and solved some of my problems in some projects I have. _But it seems to frozen now_.

I am seeing this issues and PR movements, and thought to **create a fork and implement the changes we need**. Lets evolue this project and inject the PR's **you're creating for it**!

Anyone who wants a up to date code, can help me at [https://github.com/GatoNinja/gn-dropdown-multiselect](https://github.com/GatoNinja/gn-dropdown-multiselect). For now, it's the same project, and I have the goal to make a pretty fast and clean code, Angular 1.x compatible for start.

I know I can count on you.

**Comment by pkempenaers** [comment]
Hi I've done the same in https://github.com/myforce/angularjs-dropdown-multiselect
It's probably better to contribute to that repo because most PR's (that are usefull) from here have been merged and a lot of extra features have been added

**Comment by ygorlazaro** [comment]
@pkempenaers perfect. I am forking you now and I'll help to improve this

**Comment by ygorlazaro** [comment]
@pkempenaers can you make me a contributor there?

**Comment by pkempenaers** [comment]
I'll first clean up the pending PR's and then I'll look into how I want to manage that repo (too much can break at this point -> tests need to be set up). So for now you can create PR's and I'll merge them in asap. Later on I'll look at adding contributors (in the next few weeks).

**Comment by Rafi993** [comment]
@pkempenaers  and @ygorlazaro it is a good news to hear ill contribute to that repo too 👍

**Comment by SaltyCatFish** [comment]
@pkempenaers and @ygorlazaro Good initiative fellas.

**Comment by ygorlazaro** [comment]
Thanks @Rafi993 and @SaltyCatFish.

I am in a hurry to make this project work, so I made myself a fork at [https://github.com/GatoNinja/gn-dropdown-multiselect](https://github.com/GatoNinja/gn-dropdown-multiselect).

This is now published at `npm install gn-dropdown-multiselect` and `bower install gn-dropdown-multiselect`. This is a version with some fixes already made by the community from here and another repos.

I would like all of you contributing there ❤️

**Comment by ghiscoding** [comment]
@ygorlazaro thanks for the effort but why opening a 3rd fork when there's already 2 to deal with? I'm using @pkempenaers fork with great success and there's a demo site to go with it. So I'm happy with his fork. No offense but I'm not sure what's the benefit of having a 3rd player...

**Comment by ygorlazaro** [comment]
Sure, I understand. I will concentrate my efforts at @pkempenaers' fork. I can implement some changes made to my own fork.

Now I think we only have one fork, since @dotansimha does not evolve 😄

**Comment by pkempenaers** [comment]
I've recently become collaborator of this repo :)

**Comment by ygorlazaro** [comment]
Nice!

**Comment by SaltyCatFish** [comment]
Well done
