### ISSUE TITLE
buttonDefaultText is not Working 

### ISSUE THREAD

**Issue by hardikBharadava** [dotansimha/angularjs-dropdown-multiselect#272]
@dotansimha, 
I have provided buttonDefaultText on my dropdown configs, but it is not executing provided custom text on button.
here's my extra settings, which I'm passing on dropdown.
`dynamicTitle: false,

 buttonDefaultText: "Columns",`

on this, i assume that button have to display `Projects` whatever happens, if any value of dropdown is selected or not.

![Image 1](https://cloud.githubusercontent.com/assets/8450213/19513747/a5207388-95b6-11e6-9710-9c5ad83af350.PNG)
![Image 2](https://cloud.githubusercontent.com/assets/8450213/19513727/983bf3c2-95b6-11e6-9780-beb6cd36967f.PNG)

**Comment by pkempenaers** [comment]
This is working fine for me,
Remember that buttonDefaultText is a property of translation-texts and not of extra-settings
