### ISSUE TITLE
feature request - while using Group by sort group elements

### ISSUE THREAD

**Issue by malyadrik04** [dotansimha/angularjs-dropdown-multiselect#276]
Hi, While using groupBy feature the elements under group are not in sorted order. even though we pass sorted data.

We have a solution to fix this issue as below. This will sort provided list object with group by property and groupBy elements property.
e.g: Group by **Gender** and by **Age**

//add new setting.
$scope.settings = {
....
groupByOptionsOrder: 'id'
}

//filter new data with **new setting property** along with **groupBy** property. 
$scope.orderedItems = $filter('orderBy')(newValue, [$scope.settings.groupBy , $scope.settings.groupByOptionsOrder]);

**Comment by pkempenaers** [comment]
In v2.0.0-beta.1 the groupBy works as an orderBy which takes the index of the item in the original array into account
