### ISSUE TITLE
Options are not displaying when placed inside UI-Grid

### ISSUE THREAD

**Issue by Gowthamnatanakumar** [dotansimha/angularjs-dropdown-multiselect#277]
Am new to angularjs, please help 

I am using ng-dropdown-multiselect directive and it is working perfectly fine, the issue starts only when i placed the same directive inside UI-Grid. I used cell template and placed the directive. When i click the dropdown field,  only select all and remove options are showing and my local-data is not displayed. 

Does anyone have came across this kind of issue?

**Comment by pkempenaers** [comment]
This has to do with the way how ui-grid works, there is no real work-around untill we implement appendTo, see #290
