### ISSUE TITLE
Button Text is not working {{getButtonText}}.... Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [dotansimha/angularjs-dropdown-multiselect#286]
Hi,
I am using angularjs-dropdrown-multiselect working in one page. It is not working in another page...
Can anyone help me what is the issue??

I have tried with below approaches:-

1.                 
                if (_.isUndefined($scope.selectedModel)) {
                  $scope.selectedModel = [];
                }
   In angular JS drop down multi select JS.

2.     if ($scope.settings.dynamicTitle && $scope.selectedModel && ($scope.selectedModel.length > 0 || (angular.isObject($scope.selectedModel) && _.keys($scope.selectedModel).length > 0))) {

In angular JS drop down multi select JS.

But it was solved the issues. But it is not showing the options?? Can anyone help me out?

Thanks.

**Comment by shadab08** [comment]
Make sure you instantiate your model as well.

Say if your selected model is like selected-model="selectModel", then in your controller instantiate it like $scope.selectModel = [];

**Comment by BrkCoder** [comment]
I have the same bug also,please help us,this is a bug in the script himself.
