### ISSUE TITLE
Using onItemSelect + onItemDeselect to get model reference

### ISSUE THREAD

**Issue by pur3forlyphe** [dotansimha/angularjs-dropdown-multiselect#288]
I have multiple multi selectors and was wandering when using the onItemSelect + onItemDeselect - can I access the model on the selector some how? 

This is my html - I want to access the key on my model
<div ng-dropdown-multiselect="" options="sections" selected-model="alerts[key].section" extra-settings="example2settings" events="selectSections"></div>

**Comment by pkempenaers** [comment]
setting externalIdProp to "" will pass the full selected object onItemSelect and onItemDeselect

**Comment by pur3forlyphe** [comment]
Actually maybe I should have changed the wording - I have multiple multi selectors on the page and I want to get the selected option + model id - ie, 0, 1, 2 

(not the actual code)
<dropdown selected-model="something[0]"; events="events";
<dropdown selected-model="something[1]"; events="events";
<dropdown selected-model="something[2]"; events="events";
