### ISSUE TITLE
Documention gives wrong event callback name: onUnselectAll

### ISSUE THREAD

**Issue by andrewGarson** [dotansimha/angularjs-dropdown-multiselect#29]
it should be onDeselectAll. Wasn't a big deal to read the code and figure it out, but some people would not do that.

**Comment by jitenderaswani** [comment]
thanks for sharing

**Comment by huasu** [comment]
Thanks for posting.

**Comment by lucaalex87** [comment]
On top of this, onDeselectAll calls the callback, before empty-ing the selected array :)

**Comment by jhujhul** [comment]
Thanks !

**Comment by aboelnaga** [comment]
thanks!

**Comment by mahshidy** [comment]
Thanks. You guys should get a noble prize for the time you save from the rest of the world:-p

**Comment by pkempenaers** [comment]
Documentation has been updated
