### ISSUE TITLE
Is there a way to append the dropdown to body?

### ISSUE THREAD

**Issue by arsinawaz** [dotansimha/angularjs-dropdown-multiselect#291]
Is there a way to append the dropdown to body? the same way as it is in the following example:

http://plnkr.co/edit/q35RgPeZjZYc9bZwxN3t?p=preview

The need arises from a situation when the dropdown is inside a container with fixed height and width and in that case the dropdown get cut..

any kind of help is highly appreciated?

**Comment by pkempenaers** [comment]
Currently not (I do think however that the issue you have could be resolved with some css, so if you could replicate it in a plunker I could help you write a workaround), I also don't see me implement this in the current state of the component, I'll add it as one of the items that will be done in the rewrite (#290).

**Comment by arsinawaz** [comment]
Here i have created a plunker of my case..

http://plnkr.co/edit/aZmhadlhxrWQAu4018xv?p=preview

Thank you for helping me out.

**Comment by pkempenaers** [comment]
`
.ui-grid-cell {
  overflow: visible;
}
`
seems to solve the issue when not scrolled.

**Comment by arsinawaz** [comment]
Thanks it seems a workaround, i ll work with that
