### ISSUE TITLE
No demos loading in Chrome

### ISSUE THREAD

**Issue by ChrisARaymond** [dotansimha/angularjs-dropdown-multiselect#295]
Using Version 56.0.2924.87 (64-bit) on Mac yosemite and none of the demos are loading. (They were in previous releases)

**Comment by mdsadiq** [comment]
Demo not working in chrome 56 , mac Yosemite

> Syntax Error: Token ':' not a primary expression at column 1 of the expression [::texts.selectGroup] starting at [::texts.selectGroup].

As show in console.

**Comment by mcolegro** [comment]
I don't think this is a Chrome issue.  The same error is thrown is IE and FireFox.  The page was working fine last week.

**Comment by ChrisARaymond** [comment]
@mcolegro is correct. I referred our Angular devs to this page and none of the demos are working, and the page worked fine before, which is how I found the relevant code to reference for something they are building.

**Comment by irbian** [comment]
Could be that someone uploaded his angular version? https://toddmotto.com/angular-one-time-binding-syntax/

That "::" syntax looks like is from angular 1.3

**Comment by pkempenaers** [comment]
I've indeed dropped support for angular 1.2 (1.3 and 1.4 should work but are not supported officialy)
