### ISSUE TITLE
smartButtonMaxItems issues

### ISSUE THREAD

**Issue by JuliaNsk** [dotansimha/angularjs-dropdown-multiselect#296]
After last release there is an issue with smartButtonMaxItems. It doesn't work correct, but there aren't any errors in console or smth else.

**Comment by JuliaNsk** [comment]
I think that problem is here:
						while (textWidth(result) > widthLimit) {
							if (itemsText[itemsText.length - 1] !== "...") {
								itemsText.push('...');
								result = result + "...";
							}
This while should be like: while (textWidth(result) > countLimit)

**Comment by JuliaNsk** [comment]
OffsetWidth of some elements is 0, so widthLimit is < 0 and there is a problem with  while (textWidth(result) > widthLimit)

**Comment by pkempenaers** [comment]
This should be working by now
