### ISSUE TITLE
Disable Menu?

### ISSUE THREAD

**Issue by deaftoned** [dotansimha/angularjs-dropdown-multiselect#30]
Is there any way to disable the menu?  Or maybe just show "no data" when there are no options to select from?

**Comment by OClement** [comment]
+1 
ng-disabled (ideally) should set the disabled attr on the button

In the meantime here's a (very) quick and dirty way to make it work (untested):
```
module.directive('ngDropdownMultiselectDisabled', function() {
  return {
    restrict: 'A',
    controller: function($scope, $element, $attrs) {
      var $btn;
      $btn = $element.find('button');
      return $scope.$watch($attrs.ngDropdownMultiselectDisabled, function(newVal) {
        return $btn.attr('disabled', newVal);
      });
    }
  };
});
```

**Comment by ktal90** [comment]
+1

**Comment by Sylox** [comment]
+1

**Comment by lanegoolsby** [comment]
+1

**Comment by kevincol54** [comment]
+1

**Comment by Ryudo302** [comment]
+1

**Comment by jcfiorenzano** [comment]
dont work for me, i did exactly what you said

     <div ng-dropdown-multiselect checkboxes="true" 
             extra-settings="multiselectsettings"
             options="restrictions"
             selected-model="restrictionSelecteds" id="multi_select" class="multi_select"
             ng-dropdown-multiselect-disabled="statusFilterDisabled">

     </div>

**Comment by jcfiorenzano** [comment]
Sorry, it's work perfectly I made a little mistake in the directive's code

**Comment by jcfiorenzano** [comment]
+1

**Comment by HugoOliveiraThor** [comment]
Excelent solution !!! Is work perfecty for me  and it was very simple . Thanks !!

**Comment by satyakirank** [comment]
yes it's worked

**Comment by pkempenaers** [comment]
setting disabled works at the moment (ng-disabled is something we could look into but I'd rather see that being combined with using ng-model, ng-change, ...)

**Comment by alon-s** [comment]
@OClement great solutuin!
but with just a small note - you should use the inline array notation to pass dependencies to controller (to prevent minification errors:

module.directive('ngDropdownMultiselectDisabled', function() {
  return {
    restrict: 'A',
    controller: ['$scope','$element','$attrs', function($scope, $element, $attrs) {
      var $btn;
      $btn = $element.find('button');
      return $scope.$watch($attrs.ngDropdownMultiselectDisabled, function(newVal) {
        return $btn.attr('disabled', newVal);
      });
    }]
  };
});

**Comment by OClement** [comment]
@alon-s Yes of course
I didn't mean that snippet to be "production ready" code, mostly showcasing a potential approach
But good pointing this out!

**Comment by Rawanmansour** [comment]
Please , any way to disable this dropdown when init it not when change
