### ISSUE TITLE
multiple display properties

### ISSUE THREAD

**Issue by nicon-dev** [dotansimha/angularjs-dropdown-multiselect#301]
Is it possible to set more than one display property?

At the moment I have this:

> vm.dropdownsettings = {displayProp: 'email', buttonClasses: 'btn btn-default dropdown-multiselect'};

Displays a list with emails like:

user1@gmail.com
user2@gmailcom

But I would like to display the firstname and then the email like this:

User1, user1@gmail.com
User2, user2@gmail.com

Is this possible at the moment?

Thanks in advance for every tip or hint!

**Comment by pkempenaers** [comment]
At this moment it's not possible (you can off course add a property to your object that consists of the string you want to display)

**Comment by pkempenaers** [comment]
Sorry my mistake you can specify the setting template which as default has {{option.name}}, so for you could have: {{option.name}}, {{option.email}}

**Comment by sidhujaspreet** [comment]
@pkempenaers  Could you please paste a code snippet how to use this setting template you mentioned ?
