### ISSUE TITLE
IE issue

### ISSUE THREAD

**Issue by shumaher205** [dotansimha/angularjs-dropdown-multiselect#304]
Hello. Today I tried to use dropdown and found bug in ie. When I enabled search feature, search input is disabled(I couldn't input any data)

**Comment by pkempenaers** [comment]
Could you create a plnkr where you replicate this issue so I can take a look at it?

**Comment by shumaher205** [comment]
Hello Pieter. I am so sorry/ I already found problem with ie. It was virus on my PC. I think we can close issue. Thank you very much for your time and support. The directive is very cool.

**Comment by shumaher205** [comment]
Cannot reproduce again
