### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by GC-Max** [dotansimha/angularjs-dropdown-multiselect#305]
http://dotansimha.github.io/angularjs-dropdown-multiselect/

The example website does not seem to be working at all for me. 
I am using Chrome Version 56.0.2924.87 (64-bit)

<img width="795" alt="screen shot 2017-03-03 at 16 21 53" src="https://cloud.githubusercontent.com/assets/10233281/23559047/b7dddde4-002d-11e7-8553-71ac6a850913.png">
<img width="1098" alt="screen shot 2017-03-03 at 16 22 11" src="https://cloud.githubusercontent.com/assets/10233281/23559046/b7d7922c-002d-11e7-9d13-2822e18961d9.png">

**Comment by snassoura** [comment]
I am having the same exact issue

**Comment by BrkCoder** [comment]
me too I have the same exact issue and no respond regrading this issue from the developers.

**Comment by pkempenaers** [comment]
Fixed
