### ISSUE TITLE
You have a bug in your script

### ISSUE THREAD

**Issue by BrkCoder** [dotansimha/angularjs-dropdown-multiselect#307]
I have found out it that the script has been broken lately and not working any more.
I am getting this weird message of {{getButtonText()}}  I can't understand from where is the source of this bug?
![multiselect-bug](https://cloud.githubusercontent.com/assets/5408870/23666885/e0b0281e-0364-11e7-8a4e-f92afba7453d.PNG)

**Comment by pkempenaers** [comment]
What version are you using (and what version of angular?)

**Comment by pkempenaers** [comment]
And can you replicate the issue in plnkr so I can have a closer look?

**Comment by BrkCoder** [comment]
I am using angular 1.5.8 and your latest script version which is probably : 1.11.3

**Comment by pkempenaers** [comment]
Could you please replicate it in plnkr, so that i can see what is going wrong?

**Comment by maddycr13** [comment]
@BrkCoder it could be due model not binding correctly. Have you set the selected-model properly.

**Comment by pkempenaers** [comment]
I'm closing this issue for now, if you want I can still take a look at what is going wrong if you give me some more code
