### ISSUE TITLE
TypeError: collection.some is not a function

### ISSUE THREAD

**Issue by hansiemithun** [dotansimha/angularjs-dropdown-multiselect#315]
Hi, i am facing [similar-issue](https://github.com/dotansimha/angularjs-dropdown-multiselect/issues/22). Recently download doesnt contain this change: https://github.com/dotansimha/angularjs-dropdown-multiselect/pull/60/files

Latest Version(1.11.4) link: https://github.com/dotansimha/angularjs-dropdown-multiselect/blob/master/src/angularjs-dropdown-multiselect.js#L266

This gets fixed if the earlier code gets merged with the latest version. Also once this is fixed and when i try to update the record, it throws an error as below:

```
TypeError: collection.some is not a function
    at findIndex (app.vendor-.min.js:96899)
    at Scope.$scope.isChecked (app.vendor-.min.js:96716)
    at app.vendor-.min.js:96574
    at Object.forEach (app.vendor-.min.js:1208)
    at Scope.$scope.getButtonText (app.vendor-.min.js:96573)
    at fn (eval at compile (app.vendor-.min.js:16009), <anonymous>:4:230)
    at expressionInputWatch (app.vendor-.min.js:17137)
    at Scope.$digest (app.vendor-.min.js:18711)
    at Scope.$apply (app.vendor-.min.js:18985)
    at HTMLButtonElement.<anonymous> (app.vendor-.min.js:27
```

**FYI:** selected-model is of type array

Also assist me how to have a quick fix if this is not merged at the earliest from controller?

**Comment by pkempenaers** [comment]
1.11.5 has been released

**Comment by hansiemithun** [comment]
Awesome @pkempenaers, thank you so much for your quickest response. First error has got resolved by updating, but `TypeError: collection.some is not a function` still persists while creating and updating of record. May i know what could be the cause for the same?

**Comment by pkempenaers** [comment]
Can you once again create a plnkr that replicates the issue? So that I can have a closer look?

**Comment by hansiemithun** [comment]
We get this error when we covert the label to smart text and try to save the data

**Comment by pkempenaers** [comment]
I'll really need to see some code to be able to see what is going wrong.
