### ISSUE TITLE
groupByTextProvider fires too soon

### ISSUE THREAD

**Issue by jkelleher** [dotansimha/angularjs-dropdown-multiselect#32]
First off, thanks for a great control for ng. Am finding plenty use in my app. Q - the _options_ attribute is being populated by a web api call to retrieve the dropdown contents. However, this control also employs _groupByTextProvider_ to group by a field in the data. Problem is that the _groupByTextProvider_ callback runs before the web api call returns to populate the _options_ attribute and so the grouping doesn't work.
My current workaround is to load the options data earlier in the program and have it about in readiness for the view that has the _groupByTextProvider_. Any ideas how I can delay the grouping action or otherwise fix it better than I have?
Thanks again,
John K

**Comment by pickettd** [comment]
I'm looking at version 1.5.2 right now (downloaded with Bower). You can see if it helps your situation to change line 112 from `$scope.$watch('options', function (newValue) {` to `$scope.$watchCollection('options', function (newValue) {`

This change helped my app get grouping to work better for data coming over a web api. I'm still experimenting with other modifications for the rest of my situation but thought this might help you.

**Comment by jkelleher** [comment]
@pickettd Cheers, David
