### ISSUE TITLE
groupby not working

### ISSUE THREAD

**Issue by aebmknrl** [dotansimha/angularjs-dropdown-multiselect#320]
Hi my friend, first of all thanks for your great work on this directive.

I put your sample exactly the same of your sample using groupby and does not work my friend. Please see the attached image:

 
![image](https://cloud.githubusercontent.com/assets/5152002/24115781/df8f9e5e-0d7a-11e7-8182-320a6791f508.png)

![image](https://cloud.githubusercontent.com/assets/5152002/24115835/08e1235e-0d7b-11e7-8509-a6d0a89607d3.png)

![image](https://cloud.githubusercontent.com/assets/5152002/24115819/f8da6d6c-0d7a-11e7-859c-47d98a40699c.png)

Im doing something wrong?
Thanks!

**Comment by pkempenaers** [comment]
what version of the component and of angular are you using?

**Comment by aebmknrl** [comment]
Hi my friend, I'm using angular 1.5.8

**Comment by aebmknrl** [comment]
Sorry, I close the issue by error

**Comment by pkempenaers** [comment]
And what version of the component are you using?

**Comment by aebmknrl** [comment]
According with my bower.json     "angularjs-dropdown-multiselect": "^1.11.1"

**Comment by pkempenaers** [comment]
The examples are already for version 2.0.0-beta. I'm still looking into how I'll also provide examples for v1. Previously group-by was an attribute instead of a setting property.

**Comment by aebmknrl** [comment]
Ok I understand. How can use the 2.0 version? Or.. how can use the attribute correctly on my actual version?

**Comment by pkempenaers** [comment]
in bower.json "angularjs-dropdown-multiselect": "^2.0.0-beta.1"

in current version <div ng-dropdown-multiselect="" options="example11data" selected-model="example11model" extra-settings="example11settings" group-by="gender"></div>

**Comment by aebmknrl** [comment]
Thanks for your support my friend.
