### ISSUE TITLE
Preselected model Isuue

### ISSUE THREAD

**Issue by JuliaNsk** [dotansimha/angularjs-dropdown-multiselect#323]
https://plnkr.co/edit/OI7UXW08lfN8CYm4y2r5?p=preview

1 checked but doesnt show in dropdown

**Comment by pkempenaers** [comment]
since beta.2 comparison is by reference so you need to do  
`$scope.selectedToTopModel = [$scope.selectedToTopData[0]];`

If you want I can do the comparison by id (configurable) but if you don't need it I'd rather not reimplement it. (as comparing by reference is faster)

**Comment by JuliaNsk** [comment]
So I need now use all object({id:1, name...}) instead of {Id: 1}?

**Comment by pkempenaers** [comment]
You need to have the same object in the selection array as in the options. I never have situations where this isn't possible. I know that for you it could not be the case, if so I'm willing to reïmplement the idProp feature (so working with {id: ...} where id is configurable to another property)

**Comment by JuliaNsk** [comment]
Tomorrow I will try to refactor this case in my project. I think it will be okey. I will write you after refactoring if everything is all right. Thank you.

**Comment by JuliaNsk** [comment]
Everithing is ok. One more question: smth was changed in groupBy, I have two groups: 'My projects' vs 'Other projects'. Previously it was My then Other,  and now Other than My. What should I do to sort goup names
