### ISSUE TITLE
Update dist/angularjs-dropdown-multiselect.min.js file

### ISSUE THREAD

**Issue by fosron** [dotansimha/angularjs-dropdown-multiselect#325]
Hello,

can somebody update the dist/angularjs-dropdown-multiselect.min.js file? Or make a seperate beta one. No script works properly to make a dist file.

Thanks.

**Comment by pkempenaers** [comment]
script file has been moved to component/component.js (as reflected in bower.json and package.json) I'll update the documentation to reflect this as well

**Comment by fosron** [comment]
I see. Also "bower install angular-dropdown-multiselect" install a different pacakge.

**Comment by pkempenaers** [comment]
Thanks for noticing :)
