### ISSUE TITLE
infinite loop with smartButtonText and display: inline-block

### ISSUE THREAD

**Issue by m4r71n** [dotansimha/angularjs-dropdown-multiselect#326]
Hi,

I've created a demo for reproduction: https://run.plnkr.co/vFUTKTClQMwojfgC/
It uses https://github.com/dotansimha/angularjs-dropdown-multiselect/blob/version-1/src/angularjs-dropdown-multiselect.js with one additional `console.log` in https://github.com/dotansimha/angularjs-dropdown-multiselect/blob/version-1/src/angularjs-dropdown-multiselect.js#L302
1. open your javascript console
2. select the item `abc`
3. select the item `abcdefgh`
4. now your browser will freeze

I'll try to come up with a PR

**Comment by pkempenaers** [comment]
if you make a Pr be sure to base it of the fix-1 branch, minification is not needed. If you don't seem to be able to fix it yourself give me a shout and I'll look at it myself

**Comment by pkempenaers** [comment]
Included in 1.11.8
