### ISSUE TITLE
Selected-model contains only id attribute

### ISSUE THREAD

**Issue by pravink** [dotansimha/angularjs-dropdown-multiselect#329]
I am trying to use the multiselect dropdown but when i select options my selected model only has id attribute.. 

below is my code- 
///JS
 $scope.example1model = []; 
$scope.example1data = [ {id: 1, text: 'test1', label: "David"}, {id: 2, text: 'test2', label: "Jhon"}, {id: 3, text: 'test3', label: "Danny"} ];
$scope.stringSettings = {enableSearch:true, scrollableHeight: '500px', scrollable: true};

//HTML
d i v 
ng-dropdown-multiselect="" 
options="example1data" selected-model="example1model" extra-settings="stringSettings">
/d i v

 
			  <tr ng-repeat="x in example1model">
			    <td>{{ x.id }}</td>
			    <td>{{ x.label }}</td>
			    <td>{{ x.text }}</td>
			  </tr>
			

//UI Snapshot
![incorrect-model-data](https://cloud.githubusercontent.com/assets/1962762/24386627/5a97fb0e-13bc-11e7-9591-509393165986.png)

could anyone plz let me know if i am missing any config to retrive the data? or any other solution?

**Comment by pkempenaers** [comment]
You're probably using v1 instead of v2.
For v1 to get full objects you need to set `externalIdProp` to `''`
v2 is still in beta and breaking changes can be found in changelog.md

**Comment by pravink** [comment]
Yes. Its working. Thanks a lot!

**Comment by pravink** [comment]
I have downloaded the latest codebase but still i need to add this property in settings.. 

Also, I am facing one more issue with Array of strings- all elements from the dropdown get selected even when i have clicked on a single item.

//JS -
$scope.stringModel = []; $scope.stringData = [ 'David', 'Jhon', 'Danny', ]; $scope.stringSettings = { externalIdProp : '', template: '{{option}}', smartButtonTextConverter(skip, option) { return option; }, };

//HTML
<div ng-dropdown-multiselect="" options="stringData" selected-model="stringModel" extra-settings="stringSettings"></div>

SNAPSHOT of UI
![incorrect-behaviour-of-array-of-string](https://cloud.githubusercontent.com/assets/1962762/24431881/4fbeea40-146a-11e7-8886-8489bebf8030.png)
