### ISSUE TITLE
Overriding onItemSelect/onItemDeselect

### ISSUE THREAD

**Issue by ssjkkp** [dotansimha/angularjs-dropdown-multiselect#330]
I have list of user objects containing user information in angular-dropdown-multiselect list as selected-model. When I choose users from the drop down list the model add only id's to the list. I tried bypassing this by creating custom event in onItemSelect that fetches the user from list according to the id selected but my problem is now there is both the id and the user object of the selected user in the selected-model list.
Is there a way to override onItemSelect to include only selected user object to the selected-model list?

**Comment by pkempenaers** [comment]
If you want full objects in v1, you can set `externalIdProp` to `''`
v2 is still in beta, you can find the breaking changes in changelog.md
