### ISSUE TITLE
selected-model issue

### ISSUE THREAD

**Issue by fosron** [dotansimha/angularjs-dropdown-multiselect#331]
I can't dynamically update selected-model with values (setting a new array of objects or pushing to the array). Even preseting the id's is not working. P.s my id's are string based.

**Comment by fosron** [comment]
Maybe the problem is the use of $$hashkey?

**Comment by pkempenaers** [comment]
What version are you using?

**Comment by fosron** [comment]
Release 2.0.0-beta.4

**Comment by fosron** [comment]
I tried setting `let values = [{ id: 'paid' }];`, also tried `let string = 'paid'; values = string.split(',').map((v) => { return { id: v } });`

**Comment by fosron** [comment]
```Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: regularInterceptedExpression","newVal":"...","oldVal":""}],[{"msg":"fn: regularInterceptedExpression","newVal":"","oldVal":"..."}],[{"msg":"fn: regularInterceptedExpression","newVal":"...","oldVal":""}],[{"msg":"fn: regularInterceptedExpression","newVal":"","oldVal":"..."}],[{"msg":"fn: regularInterceptedExpression","newVal":"...","oldVal":""}]]
http://errors.angularjs.org/1.4.14/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22m…dExpression%22%2C%22newVal%22%3A%22...%22%2C%22oldVal%22%3A%22%22%7D%5D%5D```

**Comment by pkempenaers** [comment]
in v2 object equality is checked by reference -> you should push objects that exist in your options array to your selection array, see #323

**Comment by fosron** [comment]
Works, thanks.
