### ISSUE TITLE
Same object should be in item as was passed in options 

### ISSUE THREAD

**Issue by AbhineetSinha** [dotansimha/angularjs-dropdown-multiselect#335]
item here is the parameter for the event onItemSelect . The properties are lost.

**Comment by pkempenaers** [comment]
What version of the component are you using?

**Comment by AbhineetSinha** [comment]
2.0.0-beta.6

**Comment by elmugrat** [comment]
I'm seeing the same problem (v2.0.0-beta.6, Angular 1.6.4), but only when I include dist/angularjs-dropdown-multiselect.min.js.  If I use component/component.js, everything works as expected.

**Comment by pkempenaers** [comment]
From now on dist/angularjs-dropdown-multiselect.min.js is the only file that should be used, if you use bower or npm you don't have to worry about this. If you don't use bower or npm, you should.
