### ISSUE TITLE
Identity property for "exists" comparison

### ISSUE THREAD

**Issue by elmugrat** [dotansimha/angularjs-dropdown-multiselect#336]
It would be really convenient to be able to configure an ID property for the displayed object to be used when determining if an option is selected instead of relying on ===.  This would be a huge win when dealing with dynamically generated content with preselected and/or disabled values.

**Comment by pkempenaers** [comment]
What do you want in the selected-model if you have something like that? Objects by reference or new objects?

**Comment by elmugrat** [comment]
Object by reference as it is now should be fine, but then it wouldn't matter if the objects originated from the same list (or in my case from the same API call), or even if they had the same complete set of properties, as long as the identity property is the same.

I was thinking of just tweaking the `contains` method...something (very) roughly like this:

```
function contains(collection, target) {
    let containsTarget = false;
    collection.some((object) => {
        if (settings.identityProp !== undefined) {
            if (object[settings.identityProp] === target[settings.identityProp]) {
                containsTarget = true;
                return true;
            }
        } else if (object === target) {
            containsTarget = true;
            return true;
        }
        return false;
    });
    return containsTarget;
}
```

**Comment by pkempenaers** [comment]
But then you could have a situation where you would have a list with a mix of objects that are actual objects out of the options list and some objects that only have the same identityProp?

**Comment by elmugrat** [comment]
Exactly.  My use case:  I get a list of all options from an API call.  From another API call I get a list of the options that are currently active.  They represent the same options, but in order to get the dropdown to preselect the right ones I have to reconstruct the list from the second API call using the objects from the first call.  It would be a lot easier if I could just say they should be compared by an ID property and have everything match up.
