### ISSUE TITLE
Pre-selecting item(s) not functioning properly

### ISSUE THREAD

**Issue by slayer3600** [dotansimha/angularjs-dropdown-multiselect#337]
First of all, thanks for the great component!

I noticed the most recent version is not pre-selecting values correctly. The drop down will say "2 checked", but nothing is checked in the dropdown. You can then re-check the item(s) that were already selected. I verified via this [Plunker](https://plnkr.co/edit/62dLCf0WnHgF78a5SKjX?p=preview) using the same code from the pre-selection example in the "Pre-selected Values" section of the documentation.

**Comment by pkempenaers** [comment]
You're right and the documentation is wrong, I've updated the documentation. (the example as it is now will work again when #336 is fixed).
