### ISSUE TITLE
Webpack 2.0 Compilation

### ISSUE THREAD

**Issue by mentierd** [dotansimha/angularjs-dropdown-multiselect#343]
Im running into an issue while trying to compile your latest beta version (2.0.0-beta.9) in my project, while using webpack 2.0. After looking at your src code, it looks like you're using ES6 and ng-annotate features (not to mention confusing since you have it sitting next to an example). In your dist folder, I see the minified version of your library, but it's not best practice to perform a minified build with an already minified file. I would suggest that you output an es-2015, non-minified build to your dist folder as well.

**Comment by pkempenaers** [comment]
from version 2.0.0-beta.10 the folder src is added to the dist folder, with a non minified version
