### ISSUE TITLE
Doesn't work without <toggle-dropdown> with beta-9

### ISSUE THREAD

**Issue by fosron** [dotansimha/angularjs-dropdown-multiselect#344]
Hello, your module stopped working after latest beta.

Code i took from example:

```
$scope.example1data = [ {id: 1, label: "David"}, {id: 2, label: "Jhon"}, {id: 3, label: "Danny"} ];
$scope.example1model = [];
$scope.example2model = [];
```
```
<div style="border: 1px solid black; padding: 10px;" ng-dropdown-multiselect="" options="example1data" selected-model="example2model"></div>
<div style="border: 1px solid black; padding: 10px;" ng-dropdown-multiselect="" options="example1data" selected-model="example1model"><toggle-dropdown>Test</toggle-dropdown></div>
```

This is what i get:
![Bug](https://www.dropbox.com/s/eq623jrbnjppfm9/Screenshot%202017-04-12%2011.40.33.png?dl=1)

I can see from the HTML that there's no proper element for the toggle, so it fails.

**Comment by fosron** [comment]
Ok, i missed the requirement for Angular 1.5. Is it possible to make it work on Angular 1.4?

**Comment by pkempenaers** [comment]
To get it to work in angular 1.4 you could add 
```
<toggle-dropdown>
  <button ng-disabled="disabled"
                type="button"
                class="dropdown-toggle"
                ng-class="settings.buttonClasses">
    {{getButtonText()}}&nbsp;<span class="caret"></span>
  </button>
<toggle-dropdown>
```
as transclusion in your div, this will result in exactly the same as the fallback that is provided in the current implementation, however transclusion fallbacks are a new feature in 1.5
I'm not planning to actively support version 1.4
