### ISSUE TITLE
if checked 1 item in dropdown i want to show item text but if more then one item is selected i want to display the itemcount 

### ISSUE THREAD

**Issue by ramey29** [dotansimha/angularjs-dropdown-multiselect#345]
if checked 1 item in dropdown I want to show item text but if more than one item is selected I want to display the item count, let me know if its possible, as I am either able to show the item count or itemText, not both.

Anyways, Thanks for the awesome plugin.

**Comment by ramey29** [comment]
@dotansimha do let me know if the above problem can be solved ?

**Comment by frankdrxn** [comment]
I would also appreciate this. 
For 0 selected I can just change the defaultValue, for 1 selected I can use smartButtonTextConverter if model ==1 to only show the name of the selected item. If model > 1 I can say how many are selected, the only downside however is it always end with ',...' so it'll look like "2 Items selected,...". 
The plugin would be perfect for me if I could just remove the ,... .

**Comment by ramey29** [comment]
@frankdrxn , can you show me how you did that , as i have created a directive for it and am using at multiple places, but my smartButtonMaxItems isnt getting updated.

$scope.$watch('selectedModel', function (val) {
                if (val.length === 1) {
                    $scope.dropdownSettings.smartButtonMaxItems = 1;
                   
                }
                 else {
                    $scope.dropdownSettings.smartButtonMaxItems = 0;
                }
            }, true);

**Comment by frankdrxn** [comment]
Sure, here is some example code:
`$scope.groupMembers = [ 
    {group:"Louffee", name: "FrankDrxn1", photo: "", id: "1"},
    {group:"Louffee", name: "FrankDrxn2", photo: "", id: "2"},
    {group:"Louffee", name: "FrankDrxn3", photo: "", id: "3"},
    {group:"Louffee", name: "FrankDrxn4", photo: "", id: "4"},
    {group:"AH", name: "Frank1", photo: "", id: "5"},
    {group:"AH", name: "Frank2", photo: "", id: "6"},
    {group:"AH", name: "Frank3", photo: "", id: "7"},
    {group:"AH", name: "Frank4", photo: "", id: "8"}
    ]
$scope.selectedGroupMembers = [];

$scope.memberDropdownSettings = {
            displayProp: 'name',
            groupBy: 'group',
            enableSearch: true,
			scrollable: true,
            keyboardControls: true,
            smartButtonMaxItems: 1,
            smartButtonTextConverter: function(){
                if($scope.selectedGroupMembers.length == 1){
                    return $scope.selectedGroupMembers[0].name + " Selected";
				}else{
					return $scope.selectedGroupMembers.length + " Members Selected";
				}
			}
        }
        $scope.memberDropdownTranslationText = {
            buttonDefaultText: 'Select Member(s)',
            searchPlaceholder: 'Filter'
        }

<div ng-dropdown-multiselect="" options="groupMembers" selected-model="selectedGroupMembers" extra-settings="memberDropdownSettings" translation-texts="memberDropdownTranslationText"></div>
`

If I have nothing selected the button will say "Select Member(s)", if I have one selected (lets say Frank1)  it'll say "Frank1 Selected" if you have more then one selected it (lets say 3) it'll say "3 Members Selected,...".

Now if only there was a way to get rid of the ",..." when multiple are selected.

**Comment by pkempenaers** [comment]
I'm going to add a function similar to the smartButtonTextConverter that instead of getting called with each option gets called with all selected options and that expects to get returned a string that will then be displayed, that way you have full control.

**Comment by pkempenaers** [comment]
From version 2.0.0-beta.10 the above has been added, please let me know if I can do more

**Comment by akshay-bbytes** [comment]
Group by issue in version 1.11.8

JS Code :
> $scope.selectByGroupData = [ 
> { id: 1, label: "David", gender: 'M' }, 
> { id: 2, label: "Jhon", gender: 'M' },
> { id: 3, label: "Lisa", gender: 'F' }, 
> { id: 4, label: "Nicole", gender: 'F' }, 
> { id: 5, label: "Danny", gender: 'M' }, 
> { id: 6, label: "Unknown", gender: 'O' } ]; 
> $scope.selectByGroupSettings = {
>           groupBy: 'gender',
> };

HTML:
```
<div ng-dropdown-multiselect="" options="selectByGroupData" selected-model="genderCollection" extra-settings="selectByGroupSettings">
                                    </div>
```
I tried by adding groupby attribute in html block also could not worked :(
Above code group by not working or if I'm missing something not sure
Please help asap
Thanks in advance..!!

**Comment by pankajBsharp** [comment]
Nope, it's not working, 
Cannot read property 'length' of undefined.

my code is something like this:

 $scope.filterByTimeOptions = [{
                id: 1,
                label: 'Today',
                selectable: false
            },
            {
                id: 2,
                label: 'This week',
                selectable: false
            },
            {
                id: 3,
                label: 'Last Week',
                selectable: false
            },
            {
                id: 4,
                label: 'This Month',
                selectable: false
            },
            {
                id: 5,
                label: 'Last Month',
                selectable: false
            }
        ],
  $scope.filterByTimeSettings = {
            scrollableHeight: '200px',
            scrollable: true,
            
            smartButtonMaxItems: 2,
            smartButtonTextConverter: function() {
                if ($scope.selectedFilterByTimeOptions.length == 1) {
                    return $scope.selectedFilterByTimeOptions[0].name;
                } else {
                    return $scope.selectedFilterByTimeOptions.length + " Selected";
                }
            }
        };

**Comment by frankdrxn** [comment]
@pankajBsharp Did you define and initialize $scope.selectedFilterByTimeOptions?

**Comment by pankajBsharp** [comment]
i defined and initialize $scope.selectedFilterByTimeOptions. my controller code is this much only, I define it.
$scope.filterByTimeModel = [];
   $scope.filterByTimeOptions = [{
                id: 1,
                label: 'Today',
                selectable: false
            },
            {
                id: 2,
                label: 'This week',
                selectable: false
            },
            {
                id: 3,
                label: 'Last Week',
                selectable: false
            },
            {
                id: 4,
                label: 'This Month',
                selectable: false
            },
            {
                id: 5,
                label: 'Last Month',
                selectable: false
            }
        ],
        $scope.selectedFilterByTimeOptions = [];
    $scope.filterByTimeSettings = {
        scrollableHeight: '200px',
        scrollable: true,
        keyboardControls: true,
        smartButtonMaxItems: 1,
        smartButtonTextConverter: function() {
            if ($scope.selectedFilterByTimeOptions.length == 1) {
                return $scope.selectedFilterByTimeOptions[0];
            } else {
                return $scope.selectedFilterByTimeOptions.length + " Selected";
            }
        }

        // enableSearch: true,

    };

<div ng-dropdown-multiselect="" options="filterByTimeOptions" ng-model="test" selected-model="filterByTimeModel" checkboxes="true" extra-settings="filterByTimeSettings" translation-texts="filterByTimeSettingsTexts">
                                                </div>

now its showing 0 Selected, 0 Selected....

**Comment by frankdrxn** [comment]
@pankajBsharp perhaps define and initialize it and see if it works. My code above worked for me and two others. I also saw that there was an update so perhaps functionality has changed. Good luck with your problem.

**Comment by pankajBsharp** [comment]
i defined and initialize $scope.selectedFilterByTimeOptions. my controller code is this much only, I define it.
$scope.filterByTimeModel = [];
$scope.filterByTimeOptions = [{
id: 1,
label: 'Today',
selectable: false
},
{
id: 2,
label: 'This week',
selectable: false
},
{
id: 3,
label: 'Last Week',
selectable: false
},
{
id: 4,
label: 'This Month',
selectable: false
},
{
id: 5,
label: 'Last Month',
selectable: false
}
],
$scope.selectedFilterByTimeOptions = [];
$scope.filterByTimeSettings = {
scrollableHeight: '200px',
scrollable: true,
keyboardControls: true,
smartButtonMaxItems: 1,
smartButtonTextConverter: function() {
if ($scope.selectedFilterByTimeOptions.length == 1) {
return $scope.selectedFilterByTimeOptions[0];
} else {
return $scope.selectedFilterByTimeOptions.length + " Selected";
}
}

    // enableSearch: true,

};
now its showing 0 Selected, 0 Selected....

**Comment by frankdrxn** [comment]
@pankajBsharp How is the HTML? Did you give the attribute selected-model the value selectedFilterByTimeOptions? It seems not to store the selected items.

**Comment by pankajBsharp** [comment]
Yes,

<div ng-dropdown-multiselect="" options="filterByTimeOptions" ng-model="test" selected-model="filterByTimeModel" checkboxes="true" extra-settings="filterByTimeSettings" translation-texts="filterByTimeSettingsTexts">
                                                </div>

**Comment by pankajBsharp** [comment]
`<div ng-dropdown-multiselect="" options="filterByTimeOptions" selected-model="filterByTimeModel" checkboxes="true" extra-settings="filterByTimeSettings" translation-texts="filterByTimeSettingsTexts">
                                                </div>`

**Comment by frankdrxn** [comment]
@pankajBsharp It seems to me like your using filterByTimeModel not selectedFilterByTimeOptions as the value for selected-model.

**Comment by pankajBsharp** [comment]
if I used selectedFilterByTimeOptions as a model it will not work.
