### ISSUE TITLE
Attribute disabled does not work

### ISSUE THREAD

**Issue by gertot** [dotansimha/angularjs-dropdown-multiselect#346]
When i set disabled attribute on the ng-dropdown-multiselect it does not work. I only get the right cursor but i can still click the toggleDropdown and can open it.

`<div ng-dropdown-multiselect=""
     options="$ctrl.entries"
     selected-model="$ctrl.selectedEntries"
     extra-settings="$ctrl.extraSettings"
     translation-texts="$ctrl.translationTexts"
     events="$ctrl.events"
     ng-disabled="$ctrl.isDisabled"></div>`

see this description : [https://baudehlo.com/2014/02/24/angular-js-ng-click-still-fires-when-div-is-ngdisabled/](https://baudehlo.com/2014/02/24/angular-js-ng-click-still-fires-when-div-is-ngdisabled/)

**Comment by pkempenaers** [comment]
we don't support ng-disabled, you can however set the disabled attribute
