### ISSUE TITLE
Can we get an un-minified version for Dist? 

### ISSUE THREAD

**Issue by aaburgos4** [dotansimha/angularjs-dropdown-multiselect#348]

**Comment by panchalkalpesh** [comment]
Don't we have **sourceMaps** already?


    //# sourceMappingURL=maps/angularjs-dropdown-multiselect.min.js.map

**Comment by pkempenaers** [comment]
I'm going to add the unminified but concatenated source to the dist folder

**Comment by pkempenaers** [comment]
from version 2.0.0-beta.10 the folder src is added to the dist folder, with a non minified version
