### ISSUE TITLE
On changing the view , the ticks are disappearing although the model is maintained  

### ISSUE THREAD

**Issue by AbhineetSinha** [dotansimha/angularjs-dropdown-multiselect#360]
I have an app wherein after doing multiple selection , different views can be selected , when the view changes the model is consistent but the ticks disappears .

**Comment by ChetnaGupta** [comment]
@AbhineetSinha did you get the fix for this issue? I am facing the same problem in IE11 browser. Sometimes the ticks mark just disappear from the drop-down selection although the model is maintained
