### ISSUE TITLE
When restoring the currently selected items from localStorage, the dropdown does not show any options as selected

### ISSUE THREAD

**Issue by zcdziura** [dotansimha/angularjs-dropdown-multiselect#364]
I am caching the `selected-model` in localStorage, and retrieving the model again on page load. When navigating back to the page with the multiselect, the component doesn't properly display the currently selected items. However, the dropdown label DOES display the number of items that are supposed to be selected.

**Comment by salmanlone** [comment]
I am having the same issue. Found something?

**Comment by salmanlone** [comment]
I have solved the issue. It is basically you need to filter the same model which you have assigned to the options in html. i.e. options="teamsData" and assign the filtered result to your selected-model="Selectedteams". following is the code for help.

`<div ng-dropdown-multiselect="" options="teamsData" selected-model="Selectedteams" extra-settings="teamsDataSettings"></div>`

`$scope.teamsData` populate all the teams for dropdown.

` angular.forEach(employeeInfo.Teams, function (team) {
                    $scope.teamsData.push({ id: team.TeamId, label: team.TeamName });
                });`

and `$scope.Selectedteams` is the model for selected teams

`for (var i = 0; i < $scope.teamsData.length; i++) {
                    if (employeeInfo.Teams[i].IsChecked && employeeInfo.Teams[i].TeamId === $scope.teamsData[i].id) {
                        $scope.Selectedteams.push($scope.teamsData[i]);
                    }
                }`

**Comment by zcdziura** [comment]
The way I ended up solving it was with the `idProperty` value that's defined in the `extra-settings` directive. That way, if you're using a list of objects as your options, you can define one of the object properties as the `idProperty`, and that will work as intended.
