### ISSUE TITLE
Images / html as options and button text

### ISSUE THREAD

**Issue by lindamarieb** [dotansimha/angularjs-dropdown-multiselect#38]
Thanks for this neat directive. If anyone's interested, I've added the ability to handle images/icons or other html as option labels and button text.

**Comment by secabhi** [comment]
hi how can i use html as option . you have any repository where i can view ur code as demo

**Comment by pkempenaers** [comment]
We have template at the moment to support this kind of thing.
We should probably use $templatecache but that should be a separate issue when needed.
