### ISSUE TITLE
Bug Object

### ISSUE THREAD

**Issue by ghost** [dotansimha/angularjs-dropdown-multiselect#386]
Hello,
 
Impossible to use this  : 
```
<div ng-dropdown-multiselect="" options="example10data" selected-model="example10model" extra-settings="example10settings"></div>

 $scope.example12model = {};
$scope.example12data = [ {id: 1, label: "David"}, {id: 2, label: "Jhon"}, {id: 3, label: "Danny"} ]; $scope.example12settings = { selectionLimit: 1, };
```
I have this error : $scope.selectedModel.indexOf is not a function :/

Thanks for your solution

**Comment by ghost** [comment]
Help please

**Comment by ramiabouzeid** [comment]
Same here, even thought i have fixed the values: example12data, example12model, example12settings

**Comment by ghost** [comment]
And the previous version ? Maybe it is a problem with last version

**Comment by ghost** [comment]
The author has changed in the beta version 2.0.0 ... . 

ExtraSettings.selectionLimit = 1 is now treated the same as all other values, so select-model does not have to be an object anymore (it should always be an array)
