### ISSUE TITLE
Please provide an example with event handlers

### ISSUE THREAD

**Issue by lindamarieb** [dotansimha/angularjs-dropdown-multiselect#39]
I've tried using onItemSelect event but it never gets called. Here are my options:

``` javascript
$scope.multiSelectSettings = {
        enableSearch: true, 
        displayProp: 'name',
        scrollableHeight: '200px',
        scrollable: true,
        buttonClasses: 'btn btn-entity-select',
        smartButtonMaxItems: 10,
        dynamicTitle: true,
        externalIdProp: '',
        events: {
            onItemSelect: function (item) {
                console.log('selected: '+item);
            }
        }
    };
```

**Comment by sharvesh** [comment]
Hi,

I'm also new to this and this worked for me.
Hope this helps 

```javascript
          $scope.yourEvents = {
                     onInitDone: function(item) {
                              console.log(item);
                         },
                     onItemDeselect: function(item) {
                              console.log(item);
                        }
             };
```

```html
<div ng-dropdown-multiselect="" options="YourData" events="yourEvents" 
     selected-model="YourModel" extra-settings="yourSettings">
</div>
```

**Comment by mnemanja** [comment]
This is more like it:

<div ng-dropdown-multiselect
     options="regions_options"
     selected-model="regions_selected"
     events="{ onItemSelect: someFunction }">

Notice that we are referencing the function, not calling it. **someFunction** - without **()**.

What I would like to know is how to get more data from the element. The **onItemSelect** callback provides the option's ID, nothing else.
What would be nice is way to provide the element's ID, not just the element option's ID.

**Comment by pkempenaers** [comment]
Using events is documented. Setting externalIdProp to "" will pass full items to events. (this should probably be documented)
