### ISSUE TITLE
Checkbox list not working on Plunker?

### ISSUE THREAD

**Issue by peterankelein** [dotansimha/angularjs-dropdown-multiselect#391]
Hi, I'm testing the DD with checkbox list and noticed the checkBoxes property in settings doesn't seem to be working on Plunker. It _does_ work in my local project, however. Anyone know of a workaround? 

http://plnkr.co/edit/guyY8gj1n9rXvOieEOyc?p=preview

**Comment by wholeinsoul** [comment]
@peterankelein : were you able to make it work ? For me it only works in the demo provided here: http://dotansimha.github.io/angularjs-dropdown-multiselect/docs/#/main 

But the same exact html/js does not work for me.

Thanks

**Comment by wholeinsoul** [comment]
Found it. It works as an attribute and not as key in settings. so change your code to:

 ```
<div ng-dropdown-multiselect="" 
         checkboxes="true"
        options="example8data" 
        selected-model="example8model" 
        extra-settings="example8settings">
      </div>

```
