### ISSUE TITLE
Feature request: onChange event

### ISSUE THREAD

**Issue by PawelDecowski** [dotansimha/angularjs-dropdown-multiselect#42]
I’d like to propose a generic `onChange` event which fires whenever one of the other events occur:
- onItemSelect
- onItemDeselect
- onSelectAll
- onUnselectAll

In many cases you don’t care how the selection changed — you only want to know that it did.

Imagine a multiple, chained dropdowns scenario, where the `n + 1`th dropdown’s items are filtered based on the selection in the `n`th dropdown. You won’t care whether an item (or all) was selected or deselected, you only want to know that the `n + 1`th dropdown’s choices need to be updated.

Currently the only way to achieve it is to bind all 4 events:

``` html
<div ng-dropdown-multiselect
     events="{
         onItemSelect: callback,
         onItemDeselect: callback,
         onSelectAll: callback,
         onUnselectAll: callback
     }"></div>
```

While the alternative using `onChange` would be much shorter:

``` html
<div ng-dropdown-multiselect
     events="{ onChange: callback }"></div>
```

**Comment by lavigupta2007** [comment]
i have an issue that
suppose i have 70 items in my dropdown and when i click selectall then **onSelectAll event**  fires 
 when i use onSelectAll event and fire any method in it then it is being called for 70 times not for 1 time .
i want call it only for 1 time not for 70 time then what should i do

**Comment by babingithub** [comment]
hi lavigupta2007,

Did you find any solution for onChange, which will be called once with all selected items (for check boxes).

**Comment by pkempenaers** [comment]
We have the onSelectionChanged event now
