### ISSUE TITLE
Document how to register the directive

### ISSUE THREAD

**Issue by ORESoftware** [dotansimha/angularjs-dropdown-multiselect#437]
How do we register the directive here:

`angular.module('app', ['ui.router', 'ngAnimate', 'ngSanitize', 'ui.bootstrap', 'ngCsv', 'ngFlash']);`

?

like this?

`angular.module('app', ['ui.router', 'ngAnimate', 'ngSanitize', 'ui.bootstrap', 'ngCsv', 'ngFlash','ngDropdownMultiselect']);`

This should be in the README right?

**Comment by Makanz** [comment]
You can see the name of the directive in point 3, in the installation description in readme. 
angular.module('app', ['**angularjs-dropdown-multiselect**']);

**Comment by ORESoftware** [comment]
yes, but using the code you just mentioned, would make it much clearer.
also, it should be:

```js
angular.module('app', ['ngDropdownMultiselect']);
```

perhaps you can create an alias in the codebase?
