### ISSUE TITLE
Model Does Not Include 'label' field

### ISSUE THREAD

**Issue by JhonJ3** [dotansimha/angularjs-dropdown-multiselect#439]
When I try to select any options from the drop-down and then print the model in the console, I see select options with 'id' fields only. The label field is missing in each of the selected objects.

//JavaScript
```
$scope.example1model = [];
$scope.example1data = [{
			id: 1,
			label: "David"
		}, {
			id: 2,
			label: "Jhon"
		}, {
			id: 3,
			label: "Danny"
		}];
```

//HTML
`<div ng-dropdown-multiselect="" options="example1data" selected-model="example1model"></div>`

![consolelog](https://user-images.githubusercontent.com/33711582/32876114-28b76b48-cabd-11e7-888d-751fae809a80.jpg)
![selectedmodel](https://user-images.githubusercontent.com/33711582/32876115-28e3fa32-cabd-11e7-9207-55423c94d085.jpg)

**Comment by JhonJ3** [comment]
I thought it was an issue but looks like this is a default behavior and is like it should be.

Solve what I wanted with the help of the following link.
https://stackoverflow.com/questions/44978774/how-can-i-set-an-entire-select-option-object-as-a-model

**Comment by hemaltandel1** [comment]
Check this setting https://github.com/dotansimha/angularjs-dropdown-multiselect/issues/365
