### ISSUE TITLE
Very slow when in a repeat

### ISSUE THREAD

**Issue by onlyafly** [dotansimha/angularjs-dropdown-multiselect#45]
I am using this in a ng-repeat. When the total number of repeats is fairly low, performance is acceptable. But once the number of elements gets above 30 or so, actions on the page become significantly slower. It appears to be due to the ng-dropdown-multiselect, as the speed problems immediately disappear when it is removed from the page.

Are there any tricks to improving the performance of the multiselect in this situation, or could this be a bug?

**Comment by cnd5041** [comment]
@onlyafly that solution worked for me as well, thanks. 
if ($scope.open) {
        ...
}

**Comment by arsinawaz** [comment]
@onlyafly thanks, it significantly improved performance.

**Comment by pikiou** [comment]
@onlyafly Great help, thanks!

**Comment by pkempenaers** [comment]
This has been fixed
