### ISSUE TITLE
onItemDeselect does not return object

### ISSUE THREAD

**Issue by simeg** [dotansimha/angularjs-dropdown-multiselect#46]
My options:
`$scope.optionsMultiSelect = {`
`displayProp: 'value', idProp:'value', externalIdProp: ''
            };`
`externalIdProp` is set to `''` so it should return an object.

`onItemSelect` returns the object. `onItemDeselect` just returns `value` which is a string.

Have I misunderstood the documentation or is this a bug?

**Comment by DavidCasillasRivero** [comment]
When setting èxternalIdProp`='' the event `onItemDeselect` is returning an object with just the `id` property, while the event `onItemSelect`returns the whole item. Inspecting the code you can see the difference:

                    if (!dontRemove && exists) {
                        $scope.selectedModel.splice(_.findIndex($scope.selectedModel, findObj), 1);
                        $scope.externalEvents.onItemDeselect(findObj);
                    } else if (!exists && ($scope.settings.selectionLimit === 0 || $scope.selectedModel.length < $scope.settings.selectionLimit)) {
                        $scope.selectedModel.push(finalObj);
                        $scope.externalEvents.onItemSelect(finalObj);
                    }

Here `finalObj` has an item with all properties (`id`, and `label`plus any other) while `findObj` just has the ìd`property. The event `onItemSelect`is being called with `finalObj`while `onItemDeselect` is called with `findObj`. 

I have modified myself the line of code for testing and everything is going ok.

Is this a bug? Will it be fixed?

**Comment by dgwaldo** [comment]
Having the same issue here... Ended up just looking up the object myself based on the id...

**Comment by pkempenaers** [comment]
Setting externalIdProp to "" will return full items instead of only id.

**Comment by pybelecalo** [comment]
Hello pkempenaers,

This bug is not fixed. Like he says DavidCasillasRivero, we are mandated  to change findObj to finalObj to resolve our problem. 

This bug must to be fixed.
