### ISSUE TITLE
TypeError when clicking SVG

### ISSUE THREAD

**Issue by samny** [dotansimha/angularjs-dropdown-multiselect#49]
When clicking inside a SVG graphic anywhere on a page with a dropdown-multiselect I get "Uncaught TypeError: undefined is not a function" on row 155 in angularjs-dropdown-multiselect.js.

It seems you can't expect className to always be a string.

```
_.contains(target.className.split(' ')
```

**Comment by levipadre** [comment]
When do you want to commit this fix?

Thanks,
L

**Comment by pkempenaers** [comment]
This has been fixed as you can see in [this plunker](https://embed.plnkr.co/xWQCgwUMigHheKmo1UjG/)
