### ISSUE TITLE
Token 'for' is an unexpected token at column 16 of the expression

### ISSUE THREAD

**Issue by avarndell** [dotansimha/angularjs-dropdown-multiselect#53]
I'm doing a repeat of "(key, value) in attribtues"  on the option I have options="attrtype.vale for attrtype in value" however I'm getting a token 'for' is an unexpected token.

my json data is as follows:
 attributes= [
                        {
                           "attributes": {
                              "Band":["800 Mhz", "1900 Mhz"],
                              "UMTS Capability":["CAT 10", "LTE"]
                         }
                      }];

**Comment by pkempenaers** [comment]
options needs to be passed an array of objects
