### ISSUE TITLE
setting translation-texts inside a directive from scope fails

### ISSUE THREAD

**Issue by benjamin0101** [dotansimha/angularjs-dropdown-multiselect#54]
I am failing to see why the fail case would not work. The only thing I have come up with is the quotes are changing from single to double in the failure case. Could someone help me understand better what might be going on? At this point it looks like a bug, but I'm pretty new to angular so wouldn't surprise me if it was my own doing.

Thanks for any help!

**my directive**

```
'use strict';

app
  .directive('preparerFilter', function () {
    return {
      templateUrl: 'templates/preparer-Filter.html',
      restrict: 'E',
      link: function postLink(scope, element, attrs) {
         scope.PreparersCustomTexts = { buttonDefaultText: 'my text' };
      }
    };
  });
```
### fails

**templates/preparer-filter.html**

```
<div 
    ng-dropdown-multiselect="" 
    ng-click="ActiveFacet='preparer'" 
    options="terms" 
    events="gridEvents" 
    selected-model="[]" 
    extra-settings="example13settings"
    translation-texts="{{ PreparersCustomTexts }}"
    blah-test="{{ PreparersCustomTexts }}" 
    checkboxes="true">
</div>

{{ PreparersCustomTexts }}
```
#### exception details

```
angular.js:11594 Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{ PreparersCustomTexts }}] starting at [{ PreparersCustomTexts }}].
http://errors.angularjs.org/1.3.8/$parse/syntax?p0=%7B&p1=invalid%20key&p2=…%7B%20PreparersCustomTexts%20%7D%7D&p4=%7B%20PreparersCustomTexts%20%7D%7D
    at http://localhost:9000/bower_components/angular/angular.js:63:12
    at Parser.throwError (http://localhost:9000/bower_components/angular/angular.js:11998:11)
    at Parser.object (http://localhost:9000/bower_components/angular/angular.js:12380:16)
    at Parser.primary (http://localhost:9000/bower_components/angular/angular.js:11968:22)
    at Parser.unary (http://localhost:9000/bower_components/angular/angular.js:12258:19)
    at Parser.multiplicative (http://localhost:9000/bower_components/angular/angular.js:12241:21)
    at Parser.additive (http://localhost:9000/bower_components/angular/angular.js:12232:21)
    at Parser.relational (http://localhost:9000/bower_components/angular/angular.js:12223:21)
    at Parser.equality (http://localhost:9000/bower_components/angular/angular.js:12214:21)
    at Parser.logicalAND (http://localhost:9000/bower_components/angular/angular.js:12205:21)
```
### works

**templates/preparer-filter.html**

```
<div 
    ng-dropdown-multiselect="" 
    ng-click="ActiveFacet='preparer'" 
    options="terms" 
    events="gridEvents" 
    selected-model="[]" 
    extra-settings="example13settings"
    translation-texts=""
    blah-test="{{ PreparersCustomTexts }}" 
    checkboxes="true">
</div>

{{ PreparersCustomTexts }}
```

**Comment by semeano** [comment]
You have to set it without the brackets, like this:

    translation-texts="PreparersCustomTexts"

But it seems that using it inside a directive isn't working either.

This **works**:
HTML:

    <div ng-dropdown-multiselect="" options="example5data" selected-model="example5model" extra-settings="example5settings" translation-texts="example5customTexts"></div>

JS:

    $scope.example5model = [];
    $scope.example5data = [ {id: 1, label: "David"}, {id: 2, label: "Jhon"}, {id: 3, label: "Danny"}];
    $scope.example5settings = {};
    $scope.example5customTexts = {buttonDefaultText: 'Select Users'};

But this **doesn't work**:
HTML:

    <div ng-dropdown-multiselect="" options="example5data" selected-model="example5model" extra-settings="example5settings" translation-texts="example5customTexts"></div>

JS:

    (function () {
	'use strict';
	angular.module('app')

		/* @ngInject */
		.directive('my-directive', function () {

		// Linker function
		function linker(scope, element, attrs) {
                   scope.example5model = [];
                   scope.example5data = [ {id: 1, label: "David"}, {id: 2, label: "Jhon"}, {id: 3, label: "Danny"}];
                   scope.example5settings = {};
                   scope.example5customTexts = {buttonDefaultText: 'Select Users'};
		}

		return {
                restrict: 'E',
                templateUrl: 'my-directive.html',
                replace: true,
                link: linker
                };
	}
    })();

**Comment by semeano** [comment]
In order to make the the example I gave to work you have to set it on the controller.

    (function () {
	'use strict';
	angular.module('app')

		.controller('my-directive-ctrl', ['$scope', function ($scope) {
                   scope.example5model = [];
                   scope.example5data = [ {id: 1, label: "David"}, {id: 2, label: "Jhon"}, {id: 3, label: "Danny"}];
                   scope.example5settings = {};
                   scope.example5customTexts = {buttonDefaultText: 'Select Users'};
             }])
		.directive('my-directive', function () {

		return {
                restrict: 'E',
                templateUrl: 'my-directive.html',
                replace: true
                };
	}
    })();

**Comment by benjamin0101** [comment]
@semeano thank you, i'll give it a try tonight. huge thanks...i've been struggling w/ this

**Comment by benjamin0101** [comment]
@semeano you said "But it seems that using it inside a directive isn't really working..."

This is a bug though...it should be able to work on a directive.

**Comment by benjamin0101** [comment]
@semeano when replace:true exists in the directive I get this error in Chrome:

Error: [$compile:multidir] Multiple directives [preparerFilter, ngDropdownMultiselect] asking for template on: <div ng-dropdown-multiselect="" options="example5data" selected-model="example5model" extra-settings="example5settings" translation-texts="example5customTexts">

Thanks again for helping out!

**Comment by semeano** [comment]
@benjamin0101 

It doesn't work inside a directive because this is what happens behind the scenes:

1. renders your directive, returning the object
2. render the dropdown-multiselect directive, with all it settings
3. the linker function is fired

What we really needed is the linker function to run before the dropdown-multiselect directive is rendered.
So, what are the options? One really good is to use a "resolve" attribute is our directive, BUT that doesn't exist (but a lot of people is asking for that [here](https://github.com/angular/angular.js/issues/2095)).

Other solution is to set the settings on the controller like I said previously, and it seems to me the best.

You can also use a promise to return your directive object after resolving your settings for the dropdown-multiselect directive but that might cause some flickers on your page.

**Comment by semeano** [comment]
@benjamin0101 about the error, it can't be because of the "replace" attribute because I'm using it just fine.

Are you using "transclude: true" ?
