### ISSUE TITLE
Check All - Check Only Filtered (searched) Options 

### ISSUE THREAD

**Issue by karthilxg** [dotansimha/angularjs-dropdown-multiselect#61]
Is there a way we can select all the filtered options only by clicking the 'Check All' button ?

For example: List has,
Apple 1,
Apple 2,
....
....
Apple 1000,
Grape,
Banana

Searching : Apple

The result would be,

Apple 1,
Apple 2,
..
...
Apple 1000

Is there a way to select all the filtered results (only list of 'Apple' ) using the Check All button ?

**Comment by harpcio** [comment]
I created own directive and changed method: 

                    $scope.selectAll = function () {
                        $scope.deselectAll(false);
                        $scope.externalEvents.onSelectAll();

                        angular.forEach($scope.options, function (value) {
                            if(value[$scope.settings.nameProp].toLowerCase().indexOf($scope.searchFilter) >= 0 ) {
                                $scope.setSelectedItem(value[$scope.settings.idProp], true);
                            }
                        });
                    };

**Comment by harpcio** [comment]
Another approach is to use decorator: 

    app.config(['$provide', function ($provide) {
        $provide.decorator('ngDropdownMultiselectDirective', function ($delegate) {
            var directive = $delegate[0];

            var link = directive.link;

            directive.compile = function () {
                return function ($scope, element, attrs) {
                    link.apply(this, arguments);

                    $scope.settings.nameProp = 'name';

                    $scope.selectAll = function () {
                        $scope.deselectAll(false);
                        $scope.externalEvents.onSelectAll();

                        angular.forEach($scope.options, function (value) {
                            if (value[$scope.settings.nameProp].toLowerCase().indexOf($scope.searchFilter) >= 0) {
                                $scope.setSelectedItem(value[$scope.settings.idProp], true);
                            }
                        });
                    };
                };
            };

            return $delegate;
        });
    }]);

**Comment by karthilxg** [comment]
@harpcio thanks!

**Comment by egbertp** [comment]
In case somebody needs the same functionality: see my fork of the package.
https://github.com/adcombi/angularjs-dropdown-multiselect

This fork does exactly what @harpcio explains. @harpcio Thanks!!!
