### ISSUE TITLE
need grouping check/uncheck features support in the dropdown options

### ISSUE THREAD

**Issue by madasuk** [dotansimha/angularjs-dropdown-multiselect#67]
Thanks for the nice plugin. But I am looking for some thing like (With Optgroups) at http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/. The drop down options should support grouping, with select all groups, select individual groups, etc features as shown in the above referred link with check boxes. In the grouping example you have provided in the demo page, male and female groups are disable for individual grouping check/uncheck.  Is it possible to achieve those features with this plugin?

**Comment by pkempenaers** [comment]
If this is a feature that you are still interested in could you please comment. Otherwise I'll close this issue after 2017/02/04
