### ISSUE TITLE
Support template url

### ISSUE THREAD

**Issue by phuongnois** [dotansimha/angularjs-dropdown-multiselect#68]
Please support template-url attribute.

**Comment by gnicol-bzh** [comment]
+1

**Comment by whatadewitt** [comment]
+1

**Comment by pkempenaers** [comment]
If this is a feature that you are still interested in could you please comment. Otherwise I'll close this issue after 2017/02/04

**Comment by gnicol-bzh** [comment]
Hi. Thank you but as far as I'mconcerned., it's too late for me, I'm not on an Angular project anymore (but I wish I was ;)). Maybe next year... or later... or never... :D

But maybe the others are still interested in...
