### ISSUE TITLE
How to catch dropdown change event in directive?

### ISSUE THREAD

**Issue by kenanyildiz** [dotansimha/angularjs-dropdown-multiselect#69]
I'm using this dropdown modules. I want to ask, how can i catch when i select item dropdown change event in directive?

I can catch event in controller, but i can not catch event in directive.. How should i use in directive?

**Comment by jaythomas** [comment]
Use `onItemSelect` attribute, like in #39 in PawelDecowski's example. There are no examples on the GitHub Pages, and the author will most likely not provide documentation for this on his GitHub Pages site as he is writing a new dropdown-multiselect module to supersede this one.

**Comment by kenanyildiz** [comment]
I'm using onItemSelect event already. There is no problem for this.. My ask, How to catch dropdown change event in directive? I catching in the Controller, its working.. but this is not good code. I want to use in Directives. Do you understand me?

**Comment by jaythomas** [comment]
That should work fine. Do you have an example of your code? Maybe a plunker?

**Comment by kmukthi** [comment]
onItemSelect works fine, but my question is can you attach a function on onItemSelect. I was successful in doing it like $scope.example9event = {onItemSelect: function(){ alert(); }}; But i want to know if can do it like $scope.example9event = {onItemSelect: $scope.myFunction()}; and i have declared the myFunction in the same controllerm, any help would be much appreciated. Thanks Mukthi

**Comment by kmukthi** [comment]
Solved it
$scope.example9event = {onItemSelect: function() { myFunction() } };
Thanks :)

**Comment by smriti-chandhok** [comment]
How can i send parameters to the events.
`<span ng-dropdown-multiselect="" options="allUsers2" selected-model="Others"  events="multiuserevents" extra-settings="multiuserSetting" translation-texts="multiuserTexts" >
                                                            </span>`

` $scope.multiuserevents = {
        onSelectionChanged: function (item) {
            $scope.myFunction(item);
        },
       
    };`

Need to pass parameters to the onSelectionChanged Event
