### ISSUE TITLE
Multiple dropdowns on a single page... how can we not let more than one box toggle at a time?

### ISSUE THREAD

**Issue by sdawson26** [dotansimha/angularjs-dropdown-multiselect#83]
I'm trying to figure out how to make a dropdown box close after another one is opened next to it. Right now, if you open one box, you have to click the document (not a sibling button) to close it.

**Comment by akm6270** [comment]
did you figure out the issue? i also need help with this

**Comment by sdawson26** [comment]
Its been a while since I've messed with this code, but I believe the problem was solved once I stopped using angularjs-dropdown-multiselect altogether. Instead, I wrote a directive that handled multi-selections.
