### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by vssathish** [dotansimha/angularjs-dropdown-multiselect#84]
I've a page with angularjs-dropdown-multiselect and dagre-d3. When i click on a svg element rendered by d3, it is intercepted by the following click event handler. The classname is an object and not a string in my case.

```
        if (_.contains(target.className.split(' '), 'multiselect-parent') && !parentFound) {
```

Adding _.isString(target.className) resolves the issue.

**Comment by prasanth270** [comment]
+1

**Comment by pkempenaers** [comment]
This has been resolved
