### ISSUE TITLE
event within ng-repeat

### ISSUE THREAD

**Issue by ShadowZ0** [dotansimha/angularjs-dropdown-multiselect#85]
try to call the event handler to trigger and update for an item within the ng-repeat but unfortunately it cannot find the item within the scope, example as follow:

<div ng-repeat="client in clients">
    <input ng-model="item.abc" ng-change="save(client)">
    <div ng-dropdown-multiselect="" ... events = "{onItemSelect: function(item) { $scope.save(client) } }">  </div>
</div>

the error in browser console would be client is not defined.. 

is there anyway to by pass this?

thanks!

**Comment by ancarius** [comment]
Well, I'm guessing you have a client variable that's not defined somewhere. If your code is wrapped, you might need to pass it as a parameter.

This isn't much to go on.
