### ISSUE TITLE
singleSelection cannot be deselected

### ISSUE THREAD

**Issue by byhoung** [dotansimha/angularjs-dropdown-multiselect#89]
If the selection limit is set to something greater than 1, you can deselect each option where the dropdown (it becomes optional), but once you change the selection limit to 1, you cannot deselect your item (it becomes mandatory) to select at least one option once you click on one. 

You might say to might as well use a normal drop-down menu in this case, but what if I need a dynamic multselection where the selection limit changes based on previous selections?

**Comment by pkempenaers** [comment]
Currently working
