### ISSUE TITLE
selecting one entry in a dropdown inside an ng-repeat updates all dropdowns in ng-repeat

### ISSUE THREAD

**Issue by cpoole** [dotansimha/angularjs-dropdown-multiselect#97]
see the codepen http://codepen.io/cpoole/pen/WvbeXm

Note that the ids for entries under the different dropdowns are the same.

Essentially click the checkboxes and then notice as you select an entry for one dropdown all other dropdowns have the entry with a matching id clicked.

If you click an entry with an ID that is not in the others (such as the last entry under teams) then the dropdown text will increment for the other dropdowns but nothing will be selected in the other dropdowns

**Comment by cpoole** [comment]
Ah, I figured it out. The model isnt just used to tell the dropdown what format the data will be in. It is actually used to store the data as well. As such you need a separate model object for each dropdown. I was sharing one model. 

Unique models fixed this.

**Comment by MauritzKruger** [comment]
@cpoole If possible, can you please post jsfiddle with your solution as I am currently struggling with the same issue. I have a ng-repeat for invoices that needs to link a facility to that invoice and this directive makes the search for the correct facility easy, but now I can't use one model for the selected facility per invoice.
Sample code:
`````
HTML:
<tr ng-repeat="invoice in invoices">
	<td class="text-center">
		<!-- Facility -->
		<ng-form name="facilityForm">
				<div
					ng-dropdown-multiselect=""
					ng-model="invoice.facilityId"
					options="facilities"
					selected-model="invoice.facilityId"
					extra-settings="multiSelectSettings">
				</div>
		</ng-form>
	</td>
</tr>

JS:
$scope.multiSelectSettings = {
	externalIdProp: 'label',
	enableSearch: true,
	showCheckAll: false,
	showUncheckAll: false,
	scrollableHeight: '300px',
	scrollable: true,
	selectionLimit: 1
};

$scope.facilities = [
	{ id: 1, label: 'Facility 01' },
	{ id: 2, label: 'Facility 02' },
	{ id: 3, label: 'Facility 03' },
	{ id: 4, label: 'Facility 04' },
	{ id: 5, label: 'Facility 05' },
	{ id: 6, label: 'Facility 06' },
	{ id: 7, label: 'Facility 07' },
	{ id: 8, label: 'Facility 08' },
];
$scope.invoices = [
	{ facilityId: null, invoiceNr: null, invoiceAmount: null }
];

$scope.addInvoiceRow = function() {
	$scope.invoices.push( { facilityId: null, invoiceNr: null, invoiceAmount: null } );
};

$scope.removeInvoiceRow = function( index ) {
	$scope.invoices.splice( index, 1 );
};
`````

**Comment by sarangdevatale** [comment]
@MauritzKruger  hi, I am also facing same problem. Did you get the answer. Please provide the code if possible. Reply

**Comment by Sudharshan-Godavarthi** [comment]
Hi @cpoole  am also facing same problem. Can you share the solution .

**Comment by saathvik160** [comment]
Hi @cpoole. Can you share the solution for this?
