### ISSUE TITLE
Cannot work with Breeze objects

### ISSUE THREAD

**Issue by christypiffat** [dotansimha/angularjs-dropdown-multiselect#99]
I am using [Breeze](http://www.getbreezenow.com/) for retrieving and querying data.  The objects returned track all changes, so they have a wrapper around the properties.  As a result, my id and label are wrapped in a JSON object called '_backingStore'.   I can't find a way to assign the displayProp and idProp using a drill-through into those properties.  Also, if I try to use extensions on the object to create properties higher up, it seems that the additional information causes the $scope.selectedModel to be undefined, which causes the getButtonText to crash.  I have created a new object that just contains the object properties I need.  This works, but it loses all Breeze caching and change tracking on this part of the main object.  Is there a way to handle using properties that are multiple levels deep in a JSON object?

I am including some of the staffList object model, which would be used to create the options.  The entityAspect is what tracks the information, and StaffName is an extension I added.
![image](https://cloud.githubusercontent.com/assets/4719322/7422701/708f43ec-ef54-11e4-96e5-654dc4684b38.png)

Thanks!

**Comment by pkempenaers** [comment]
In 2.0.0-beta we compare objects by reference, and using the template options you have more control over the properties you want to display
